import Foundation

/// Catalogue de titres pour le mode démo. Valeurs éditoriales issues de la table
/// `securities` seedée depuis le prototype (`supabase/seed/securities.sql`). En
/// mode connecté, ce catalogue sera remplacé par la lecture de Supabase.
///
/// `logoAsset` doit porter le nom d'un imageset présent dans le catalogue —
/// `KrzSecurityBadge` retombe silencieusement sur les initiales quand l'image
/// est absente, ce qui rend un oubli invisible. Les logos s'importent avec
/// `tools/import_design_assets.py`.
enum DemoCatalog {
    static let stocks: [StockInfo] = [
        StockInfo(symbol: "NVDA", name: "Nvidia", cc: "US", sector: "Semi-conducteurs · IA",
                  sectorEn: "Semiconductors · AI",
                  founded: "1993", dividendYield: 0.03, mcap: "3 900 Md$", pe: nil, peg: nil,
                  ceo: "Jensen Huang",
                  what: "Nvidia conçoit les processeurs graphiques qui entraînent et font tourner l'intelligence artificielle dans le monde entier.",
                  hercule: "Quand vous utilisez une IA ou jouez à un jeu récent, une puce Nvidia travaille souvent derrière. Vous possédez une part de cette machine-là.",
                  whatEn: "Nvidia designs the graphics processors that train and run artificial intelligence around the world.",
                  herculeEn: "When you use an AI or play a recent game, an Nvidia chip is often working behind the scenes. You own a share of that machinery.",
                  logoAsset: "logo-nvidia", initials: "NV", tileHex: 0x1F2A44,
                  open: 163.10, price: 165.42),
        StockInfo(symbol: "AI", name: "Air Liquide", cc: "FR", sector: "Gaz industriels",
                  sectorEn: "Industrial gases",
                  founded: "1902", dividendYield: 2.9, mcap: "112 Md€", pe: nil, peg: nil,
                  ceo: "François Jackow",
                  what: "Air Liquide produit les gaz industriels — oxygène, hydrogène, azote — indispensables aux hôpitaux, aux usines et à la transition énergétique.",
                  hercule: "L'oxygène des hôpitaux français ? Souvent Air Liquide. Une entreprise discrète qui augmente son dividende depuis plus de 30 ans.",
                  whatEn: "Air Liquide produces the industrial gases — oxygen, hydrogen, nitrogen — that hospitals, factories and the energy transition depend on.",
                  herculeEn: "The oxygen in French hospitals? Often Air Liquide. A quiet company that has raised its dividend for over 30 years.",
                  logoAsset: nil, initials: "AL", tileHex: 0x0F3D6E, open: 179.60, price: 178.90),
        StockInfo(symbol: "MC", name: "LVMH", cc: "FR", sector: "Luxe",
                  sectorEn: "Luxury",
                  founded: "1987", dividendYield: 1.8, mcap: "340 Md€", pe: 22.4, peg: 2.3,
                  ceo: "Bernard Arnault",
                  what: "LVMH réunit Louis Vuitton, Dior, Moët & Chandon et des dizaines de maisons de luxe.",
                  hercule: "Un sac acheté à Paris, Tokyo ou New York fait souvent la même chose : rentrer dans le chiffre d'affaires de LVMH.",
                  whatEn: "LVMH brings together Louis Vuitton, Dior, Moët & Chandon and dozens of other luxury houses.",
                  herculeEn: "A bag bought in Paris, Tokyo or New York usually does the same thing: land in LVMH's revenue.",
                  logoAsset: nil, initials: "LV", tileHex: 0x0D1B3C, open: 618.50, price: 612.00),
        StockInfo(symbol: "RMS", name: "Hermès", cc: "FR", sector: "Luxe-maroquinerie",
                  sectorEn: "Luxury leather goods",
                  founded: "1837", dividendYield: 1.2, mcap: "184 Md€", pe: 38.5, peg: 3.1,
                  ceo: "Axel Dumas",
                  what: "Hermès fabrique des sacs, carrés de soie et articles de maroquinerie de très haut de gamme.",
                  hercule: "Une liste d'attente pour un sac Birkin : la rareté organisée fait partie du modèle d'Hermès.",
                  whatEn: "Hermès makes bags, silk scarves and leather goods at the very top of the market.",
                  herculeEn: "A waiting list for a Birkin bag: organised scarcity is part of the Hermès model.",
                  logoAsset: nil, initials: "HR", tileHex: 0x5A3210, open: 2248.00, price: 2285.00),
        StockInfo(symbol: "TTE", name: "TotalEnergies", cc: "FR", sector: "Énergie-pétrole",
                  sectorEn: "Energy and oil",
                  founded: "1924", dividendYield: 4.2, mcap: "156 Md€", pe: 6.5, peg: 0.8,
                  ceo: "Patrick Pouyanné",
                  what: "TotalEnergies produit pétrole et gaz et développe des énergies renouvelables à grande échelle.",
                  hercule: "Le plein d'essence à la pompe TotalEnergies rejoint directement les revenus de cette action.",
                  whatEn: "TotalEnergies produces oil and gas and develops renewable energy at scale.",
                  herculeEn: "Filling up at a TotalEnergies pump feeds straight into this company's revenue.",
                  logoAsset: nil, initials: "TT", tileHex: 0xB01818, open: 68.90, price: 70.40),
        StockInfo(symbol: "SAF", name: "Safran", cc: "FR", sector: "Aéronautique-défense",
                  sectorEn: "Aerospace and defence",
                  founded: "1959", dividendYield: 1.3, mcap: "68 Md€", pe: 28.5, peg: 2.7,
                  ceo: "Olivier Andriès",
                  what: "Safran fabrique des moteurs d'avion et des équipements aéronautiques.",
                  hercule: "La plupart des Airbus A320 volent avec des moteurs co-conçus par Safran.",
                  whatEn: "Safran builds aircraft engines and aerospace equipment.",
                  herculeEn: "Most Airbus A320s fly with engines co-designed by Safran.",
                  logoAsset: nil, initials: "SF", tileHex: 0x14324F, open: 195.80, price: 198.60),
        StockInfo(symbol: "AAPL", name: "Apple", cc: "US", sector: "Technologie grand public",
                  sectorEn: "Consumer technology",
                  founded: "1976", dividendYield: 0.4, mcap: "3 400 Md$", pe: nil, peg: nil,
                  ceo: "Tim Cook",
                  what: "Apple conçoit l'iPhone, le Mac et les services associés — l'un des écosystèmes les plus rentables au monde.",
                  hercule: "Chaque iPhone vendu fait un peu tourner cette action, l'une des plus grosses capitalisations de l'histoire.",
                  whatEn: "Apple designs the iPhone, the Mac and the services around them — one of the most profitable ecosystems in the world.",
                  herculeEn: "Every iPhone sold turns this stock a little, one of the largest market caps in history.",
                  logoAsset: nil, initials: "AA", tileHex: 0x1C1C1E, open: 222.80, price: 224.50),
        StockInfo(symbol: "MSFT", name: "Microsoft", cc: "US", sector: "Logiciels · Cloud",
                  sectorEn: "Software · Cloud",
                  founded: "1975", dividendYield: 0.7, mcap: "3 500 Md$", pe: nil, peg: nil,
                  ceo: "Satya Nadella",
                  what: "Microsoft édite Windows, Office et Azure, son cloud utilisé par des millions d'entreprises.",
                  hercule: "Le cloud Azure et l'IA Copilot sont devenus les principaux moteurs de croissance de Microsoft.",
                  whatEn: "Microsoft publishes Windows, Office and Azure, its cloud used by millions of businesses.",
                  herculeEn: "The Azure cloud and Copilot AI have become Microsoft's main growth engines.",
                  logoAsset: nil, initials: "MS", tileHex: 0x1F2A44, open: 465.00, price: 468.20),
        StockInfo(symbol: "SAN", name: "Sanofi", cc: "FR", sector: "Pharmaceutique",
                  sectorEn: "Pharmaceuticals",
                  founded: "2004", dividendYield: 2.9, mcap: "132 Md€", pe: 18.4, peg: 1.7,
                  ceo: "Paul Hudson",
                  what: "Sanofi développe et produit des médicaments et vaccins distribués dans plus de 100 pays.",
                  hercule: "Un vaccin de la grippe ou un traitement du diabète porte peut-être la marque de ce laboratoire français.",
                  whatEn: "Sanofi develops and produces medicines and vaccines distributed in more than 100 countries.",
                  herculeEn: "A flu vaccine or a diabetes treatment may well carry the mark of this French laboratory.",
                  logoAsset: nil, initials: "SA", tileHex: 0x6A2C8F, open: 82.40, price: 83.90),
        StockInfo(symbol: "SU", name: "Schneider Electric", cc: "FR", sector: "Automatisme-électricité",
                  sectorEn: "Automation and electrical",
                  founded: "1836", dividendYield: 2.1, mcap: "92 Md€", pe: 29.3, peg: 2.6,
                  ceo: "Olivier Blum",
                  what: "Schneider Electric fabrique des équipements de gestion de l'énergie et d'automatisation industrielle.",
                  hercule: "Le tableau électrique de votre immeuble a de bonnes chances de venir de Schneider Electric.",
                  whatEn: "Schneider Electric makes energy management and industrial automation equipment.",
                  herculeEn: "The electrical panel in your building has a good chance of coming from Schneider Electric.",
                  logoAsset: nil, initials: "SU", tileHex: 0x2E7D32, open: 248.50, price: 252.40),
        StockInfo(symbol: "BNP", name: "BNP Paribas", cc: "FR", sector: "Banque",
                  sectorEn: "Banking",
                  founded: "2000", dividendYield: 2.4, mcap: "68 Md€", pe: 8.1, peg: 1.2,
                  ceo: "Jean-Laurent Bonnafé",
                  what: "BNP Paribas est la première banque de la zone euro par le total de bilan.",
                  hercule: "Les banques sont sensibles aux taux : quand ils montent, leurs marges progressent souvent.",
                  whatEn: "BNP Paribas is the largest bank in the eurozone by total assets.",
                  herculeEn: "Banks are sensitive to rates: when rates rise, their margins often widen.",
                  logoAsset: nil, initials: "BN", tileHex: 0x00875A, open: 62.50, price: 63.30),
        StockInfo(symbol: "MC2", name: "Michelin", cc: "FR", sector: "Pneumatiques-caoutchouc",
                  sectorEn: "Tyres and rubber",
                  founded: "1889", dividendYield: 3.4, mcap: "31 Md€", pe: 7.9, peg: 1.0,
                  ceo: "Florent Menegaux",
                  what: "Michelin conçoit et fabrique des pneumatiques pour voitures, poids lourds et avions.",
                  hercule: "Le guide gastronomique et les pneus, c'est la même entreprise — un pari de communication vieux d'un siècle.",
                  whatEn: "Michelin designs and manufactures tyres for cars, trucks and aircraft.",
                  herculeEn: "The restaurant guide and the tyres are the same company — a marketing bet a century old.",
                  logoAsset: nil, initials: "MI", tileHex: 0x1B3A6B, open: 29.40, price: 29.95),
        StockInfo(symbol: "OR", name: "L'Oréal", cc: "FR", sector: "Cosmétiques-beauté",
                  sectorEn: "Cosmetics and beauty",
                  founded: "1909", dividendYield: 1.8, mcap: "188 Md€", pe: 42.1, peg: 3.5,
                  ceo: "Nicolas Hieronimus",
                  what: "L'Oréal est le numéro un mondial des cosmétiques, avec Lancôme, Garnier et bien d'autres.",
                  hercule: "Un shampooing ou un rouge à lèvres acheté quelque part dans le monde fait souvent tourner cette action.",
                  whatEn: "L'Oréal is the world's number one in cosmetics, with Lancôme, Garnier and many more.",
                  herculeEn: "A shampoo or a lipstick bought anywhere in the world often keeps this stock turning.",
                  logoAsset: nil, initials: "OR", tileHex: 0x111111, open: 398.50, price: 403.80),
        StockInfo(symbol: "ENGI", name: "Engie", cc: "FR", sector: "Énergie-services",
                  sectorEn: "Energy and services",
                  founded: "1811", dividendYield: 3.2, mcap: "38 Md€", pe: 13.6, peg: 1.4,
                  ceo: "Catherine MacGregor",
                  what: "Engie produit et distribue de l'électricité et du gaz, avec un virage marqué vers les renouvelables.",
                  hercule: "Votre facture d'énergie finance en partie la transition d'Engie vers le solaire et l'éolien.",
                  whatEn: "Engie produces and distributes electricity and gas, with a marked shift towards renewables.",
                  herculeEn: "Your energy bill partly funds Engie's shift to solar and wind.",
                  logoAsset: nil, initials: "EN", tileHex: 0x0072CE, open: 12.45, price: 12.80),
    ]
}
