-- Traduction anglaise du référentiel titres — écrite à la main, à partir du
-- français de `securities.sql` (lui-même généré depuis le prototype).
--
-- Trois colonnes : `sector_en` (libellé d'affichage — le français de `sector`
-- reste la donnée de référence, voir 0010), `description_en` et
-- `hercule_note_en`. Le reste de la ligne n'est pas touché.
--
-- À appliquer APRÈS `securities.sql` et la migration `0010_sector_en.sql`.
-- Les titres absents de la liste gardent des colonnes `*_en` à NULL : le
-- client retombe alors sur le français.
--
-- Textes en $$…$$ (dollar-quoting) : l'anglais est plein d'apostrophes, les
-- doubler une par une est une source d'erreurs silencieuses.

update public.securities as s
set sector_en      = t.sector_en,
    description_en = t.description_en,
    hercule_note_en = t.hercule_note_en,
    updated_at     = now()
from (values
  ('NVDA', $$Semiconductors · AI$$,
   $$Nvidia designs the graphics processors that train and run artificial intelligence worldwide — from data centres to self-driving cars.$$,
   $$When you use an AI or play a recent video game, chances are an Nvidia chip is working behind the scenes. You own a piece of that machinery.$$),
  ('AI', $$Industrial gases$$,
   $$Air Liquide produces the industrial gases — oxygen, hydrogen, nitrogen — that hospitals, factories and the energy transition cannot do without.$$,
   $$The oxygen in French hospitals? Often Air Liquide. A quiet company, present everywhere, that has raised its dividend for more than 30 years.$$),
  ('AAPL', $$Consumer technology$$,
   $$Apple designs the iPhone, the Mac and the services around them — one of the most profitable ecosystems in the world.$$,
   $$Every iPhone sold moves this stock a little. Apple is one of the largest market capitalisations in stock market history.$$),
  ('MSFT', $$Software · Cloud$$,
   $$Microsoft publishes Windows, Office and Azure, its cloud used by millions of companies around the world.$$,
   $$The Azure cloud and Copilot AI have become Microsoft's main growth engines.$$),
  ('GOOG', $$Internet · Advertising$$,
   $$Alphabet owns Google, YouTube and Android — the digital front door for billions of people.$$,
   $$Every Google search or YouTube video generates advertising: that is the heart of Alphabet's business model.$$),
  ('AMZN', $$E-commerce · Cloud$$,
   $$Amazon sells online and rents out the computing power of its AWS cloud to the largest companies in the world.$$,
   $$The parcel arriving tomorrow and the website you visited today may both be running on Amazon's servers.$$),
  ('TSLA', $$Automotive · Energy$$,
   $$Tesla designs electric cars and batteries, and aims to speed up the global energy transition.$$,
   $$Tesla is a volatile stock: its swings can be two to three times larger than the market average.$$),
  ('MC', $$Luxury$$,
   $$LVMH brings together Louis Vuitton, Dior, Moët & Chandon and dozens of other luxury houses.$$,
   $$A bag bought in Paris, Tokyo or New York usually does the same thing: land in LVMH's revenue.$$),
  ('AC', $$Hotels and tourism$$, NULL, NULL),
  ('AIRB', $$Aerospace and defence$$,
   $$Airbus builds the A320 and A350 airliners, as well as helicopters and satellites.$$,
   $$One in two aircraft in European skies carries the Airbus logo. An order book measured in years.$$),
  ('MT', $$Metals and mining$$,
   $$ArcelorMittal is the world's second-largest steel producer, present in construction and the car industry.$$,
   $$The price of steel closely tracks global industrial activity — a cyclical stock by nature.$$),
  ('CS', $$Insurance$$,
   $$AXA insures individuals and companies around the world against health, motor and home risks.$$,
   $$Every motor or home policy signed moves this stock a little — a model built on pooling risk.$$),
  ('BNP', $$Banking$$,
   $$BNP Paribas is the euro zone's largest bank by total assets, present in more than 60 countries.$$,
   $$Banks are sensitive to interest rates: when rates rise, their margins often widen.$$),
  ('BOUY', $$Construction$$,
   $$Bouygues builds buildings and infrastructure, and also owns TF1 and the telecoms operator Bouygues Telecom.$$,
   $$A rare conglomerate: construction, media and telecoms under one roof — three different engines.$$),
  ('BVI', $$Inspection and certification$$,
   $$Bureau Veritas inspects and certifies the quality and compliance of products, ships and buildings worldwide.$$,
   $$Every safety standard checked somewhere in the world may involve Bureau Veritas.$$),
  ('CAPG', $$IT services$$,
   $$Capgemini advises on and builds IT systems for large companies around the world.$$,
   $$The digital transformation of large companies often runs through providers like Capgemini.$$),
  ('CARR', $$Food retail$$,
   $$Carrefour operates hypermarkets, supermarkets and convenience stores in France and internationally.$$,
   $$Every shop at a Carrefour store feeds directly into this stock's revenue.$$),
  ('BN', $$Food products$$,
   $$Danone makes yoghurts, mineral waters and infant formula sold around the world.$$,
   $$A pot of yoghurt, a bottle of Evian: everyday gestures that keep this stock turning.$$),
  ('FGR', $$Construction and concessions$$,
   $$Eiffage builds roads, buildings and motorways, and operates motorway concessions.$$,
   $$The motorway tolls you pay partly fund groups like Eiffage.$$),
  ('ENGI', $$Energy and services$$,
   $$Engie produces and distributes electricity and gas, with a marked shift towards renewables.$$,
   $$Your energy bill partly funds Engie's shift towards solar and wind.$$),
  ('EFX', $$Eyewear and optics$$,
   $$EssilorLuxottica designs corrective lenses and brand-name eyewear such as Ray-Ban and Oakley.$$,
   $$One pair of glasses in three worldwide bears the mark of this French-Italian group.$$),
  ('ERF', $$Testing laboratories$$,
   $$Eurofins analyses food, medicines and environmental samples in thousands of laboratories.$$,
   $$A screening test or a food analysis often goes through a Eurofins laboratory without you knowing.$$),
  ('ENX', $$Exchanges and financial services$$,
   $$Euronext runs the exchanges of Paris, Amsterdam, Brussels, Dublin, Lisbon, Milan and Oslo.$$,
   $$When you buy a French share, the order often travels through Euronext's servers.$$),
  ('RMS', $$Luxury leather goods$$,
   $$Hermès makes bags, silk scarves and leather goods at the very top of the market.$$,
   $$A waiting list for a Birkin bag: organised scarcity is part of the Hermès business model.$$),
  ('KER', $$Luxury fashion$$,
   $$Kering brings together Gucci, Saint Laurent and Balenciaga, among other fashion and luxury houses.$$,
   $$Gucci's success or struggles weigh heavily on this stock, its most important brand.$$),
  ('OREAL', $$Cosmetics and beauty$$,
   $$L'Oréal is the world's number one in cosmetics, with brands such as Lancôme and Garnier.$$,
   $$A shampoo or a lipstick bought somewhere in the world often keeps this stock turning.$$),
  ('LR', $$Electrical equipment$$,
   $$Legrand makes electrical sockets, switches and equipment for smart buildings.$$,
   $$The socket in your wall may well have been made by Legrand, without you ever noticing.$$),
  ('ML', $$Tyres and rubber$$,
   $$Michelin designs and manufactures tyres for cars, trucks and aircraft.$$,
   $$The famous restaurant guide and the tyres are the same company — a communications bet more than a century old.$$),
  ('ORAN', $$Telecommunications$$,
   $$Orange is France's leading telecoms operator, with mobile, internet and fibre businesses.$$,
   $$Your mobile plan or your internet box may be paying this stock's dividend directly.$$),
  ('RI', $$Drinks and spirits$$,
   $$Pernod Ricard makes spirits such as Ricard, Absolut and Chivas Regal, sold around the world.$$,
   $$A stock heavily exposed to China and the United States: two key markets for premium spirits.$$),
  ('PUB', $$Advertising and marketing$$,
   $$Publicis creates advertising campaigns and marketing strategies for major global brands.$$,
   $$The next advert that catches your eye may have been dreamt up by an agency in the Publicis group.$$),
  ('RNO', $$Automotive$$,
   $$Renault designs and manufactures passenger cars and vans, including a growing electric range.$$,
   $$The diamond on the bonnet is one of the oldest symbols of the French car industry, still in the middle of its electric shift.$$),
  ('SAF', $$Aerospace and defence$$,
   $$Safran makes aircraft engines and aerospace equipment, often alongside General Electric.$$,
   $$Most Airbus A320s fly with engines co-designed by Safran — a key position in aerospace.$$),
  ('SGO', $$Construction materials$$,
   $$Saint-Gobain has been making glass, insulation and building materials for more than 350 years.$$,
   $$The pane in your window or the insulation in your roof may come from this three-hundred-year-old company.$$),
  ('SAN', $$Pharmaceuticals$$,
   $$Sanofi develops and produces medicines and vaccines distributed in more than 100 countries.$$,
   $$A flu vaccine or a diabetes treatment may well carry the mark of this French laboratory.$$),
  ('SU', $$Automation and electrical$$,
   $$Schneider Electric makes energy management and industrial automation equipment.$$,
   $$The electrical panel in your building has a good chance of coming from Schneider Electric.$$),
  ('GLE', $$Banking$$,
   $$Société Générale is one of the large French banks, active in retail and investment banking.$$,
   $$A current account, a bank card: everyday banking for millions of people in France.$$),
  ('STLA', $$Automotive$$,
   $$Stellantis brings together Peugeot, Citroën, Fiat, Jeep and 12 other car brands.$$,
   $$Fourteen brands under one roof: a very diversified stock, but exposed to the car industry's cycles.$$),
  ('STM', $$Semiconductors$$,
   $$STMicroelectronics designs electronic chips used in the car industry and in manufacturing.$$,
   $$The sensors that fire your car's airbag may come from an STMicroelectronics chip.$$),
  ('HO', $$Aerospace and defence$$,
   $$Thales designs electronic systems for defence, aerospace and space.$$,
   $$Radars, navigation systems, satellites: a stock at the heart of France's critical technologies.$$),
  ('TTE', $$Energy and oil$$,
   $$TotalEnergies produces oil and gas and develops renewable energy at scale.$$,
   $$Filling up at a TotalEnergies pump feeds straight into this stock's revenue.$$),
  ('URW', $$Retail property$$,
   $$Unibail-Rodamco-Westfield owns and manages large shopping centres in Europe and the United States.$$,
   $$Every rent paid by a shopping centre store keeps this property stock turning.$$),
  ('VIE', $$Environment and water$$,
   $$Veolia manages water, waste and energy for cities and industry around the world.$$,
   $$The water from your tap and the bins collected near you often pass through Veolia.$$),
  ('DG', $$Construction and concessions$$,
   $$Vinci builds infrastructure and operates motorway and airport concessions.$$,
   $$The world's largest construction and concessions group — from roads to airports, a sprawling presence.$$),
  ('DSY', $$3D design software$$,
   $$Dassault Systèmes publishes 3D design software used in aerospace, the car industry and healthcare.$$,
   $$Many aircraft and cars are first designed virtually on Dassault Systèmes software.$$),
  ('ETF500', $$ETF · US equities$$,
   $$This fund replicates the S&P 500, the index of the 500 largest American companies, in a single share.$$,
   $$Instead of picking one American stock, you own 500 at once — the simplest diversification there is.$$),
  ('ETFCAC', $$ETF · French equities$$,
   $$This fund tracks the CAC 40, the 40 largest companies listed in Paris.$$,
   $$An investor starting out in France often starts here: a full sweep of the French stock market.$$),
  ('ETFNAS', $$ETF · US tech equities$$,
   $$This fund replicates the Nasdaq 100, dominated by the largest American technology companies.$$,
   $$Nvidia, Apple, Microsoft: several of your individual stocks are already inside this single fund.$$),
  ('ETFWLD', $$ETF · Global equities$$,
   $$This fund replicates more than 1,500 companies across 23 developed countries.$$,
   $$This is often the first investment suggested to a beginner: the whole developed world in a single share.$$),
  ('ETFEM', $$ETF · Emerging market equities$$,
   $$This fund brings together companies from China, India, Brazil and other emerging countries.$$,
   $$Often stronger growth, but also more volatility: a complement, not the base of a portfolio.$$),
  ('ETFEU', $$ETF · European equities$$,
   $$This fund tracks 600 large and mid-sized European companies, across every sector.$$,
   $$From LVMH to Nestlé by way of SAP: the whole of Europe in a single portfolio line.$$),
  ('ETFNRG', $$ETF · Clean energy$$,
   $$This fund brings together companies in wind power, solar power and smart electricity grids.$$,
   $$A way to back the energy transition without having to pick a single company in the sector.$$),
  ('ETFGLD', $$ETF · Commodities$$,
   $$This fund holds physical gold stored in a vault, and its price follows the metal.$$,
   $$Gold is often used as a safe haven when equity markets turn nervous.$$),
  ('ETFBND', $$ETF · US bonds$$,
   $$This fund lends to the American state through bonds, in exchange for regular income.$$,
   $$A steadier building block than a share, useful for cushioning a portfolio's jolts.$$),
  ('ETFCORP', $$ETF · European bonds$$,
   $$This fund lends to large European companies through their bonds.$$,
   $$More predictable income than a share, with generally lower risk.$$),
  ('ETFNKY', $$ETF · Japanese equities$$,
   $$This fund replicates the Nikkei 225, the flagship index of the Tokyo stock exchange.$$,
   $$Toyota, Sony, Nintendo: the listed Japanese economy in a single share.$$),
  ('ETFWTR', $$ETF · Water theme$$,
   $$This fund brings together companies active in water treatment and distribution.$$,
   $$A scarce, essential resource, carried by needs that never go away.$$),
  ('ETFCYBR', $$ETF · Cybersecurity$$,
   $$This fund brings together companies specialising in data and network protection.$$,
   $$Every cyberattack that makes the headlines is a reminder of why this sector keeps growing.$$),
  ('ETFROBO', $$ETF · Robotics & AI$$,
   $$This fund brings together companies that design robots and automated systems.$$,
   $$From the automated factory to the robotic surgical arm, a bet on automating the world.$$),
  ('ETFSEMI', $$ETF · Semiconductors$$,
   $$This fund brings together the world's largest makers of electronic chips.$$,
   $$Nvidia sits there alongside dozens of other companies in the same sector — a broader bet on AI.$$),
  ('ETFHLTH', $$ETF · Healthcare$$,
   $$This fund brings together pharmaceutical laboratories and medical technology companies.$$,
   $$A sector seen as defensive: people keep looking after their health, even in an economic crisis.$$),
  ('ETFREIT', $$ETF · Listed property$$,
   $$This fund brings together companies that own and manage property and are listed on the stock market.$$,
   $$A way to invest in property without buying a physical building or managing a tenant.$$),
  ('ETFSCEU', $$ETF · Small caps$$,
   $$This fund brings together smaller European companies, less familiar to the general public.$$,
   $$More growth potential, but also more volatility than an index of large companies.$$),
  ('ETFIND', $$ETF · Indian equities$$,
   $$This fund brings together the largest companies listed in India.$$,
   $$One of the fastest-growing economies in the world, in a single share.$$),
  ('ETFCHN', $$ETF · Chinese equities$$,
   $$This fund brings together the largest listed Chinese companies, including several technology giants.$$,
   $$An enormous market, but also more sensitive to political decisions than most.$$),
  ('ETFINFRA', $$ETF · Infrastructure$$,
   $$This fund brings together companies that build and operate roads, airports and power grids.$$,
   $$Income that is often stable and regular, tied to long-term contracts.$$),
  ('ETFESG', $$ETF · Responsible investing$$,
   $$This fund selects the companies rated highest on environmental, social and governance criteria.$$,
   $$The diversification of a global index, filtered through responsibility criteria.$$),
  ('ETFLUX', $$ETF · Luxury & consumer$$,
   $$This fund brings together the world's largest luxury brands, from fashion to jewellery.$$,
   $$LVMH, Hermès, Kering and other houses gathered into a single share.$$),
  ('ETFBIO', $$ETF · Biotechnology$$,
   $$This fund brings together companies developing innovative treatments and therapies.$$,
   $$A sector with strong potential, but where every clinical trial result can move prices.$$),
  ('ETFDEF', $$ETF · Defence & aerospace$$,
   $$This fund brings together companies active in defence, aerospace and security.$$,
   $$A sector lifted by rising military budgets in several countries in recent years.$$),
  ('ETFSLV', $$ETF · Commodities$$,
   $$This fund holds physical silver stored in a vault, and its price follows the metal.$$,
   $$Often compared with gold, but more volatile and more widely used in industry.$$),
  ('ETFDIV', $$ETF · Global dividends$$,
   $$This fund brings together companies worldwide known for paying high, regular dividends.$$,
   $$A source of regular income, useful for anyone looking for payouts rather than pure growth.$$),
  ('ETFUK', $$ETF · UK equities$$,
   $$This fund replicates the FTSE 100, the 100 largest companies listed in London.$$,
   $$A long-established market, rich in commodity and financial stocks.$$),
  ('ETFDAX', $$ETF · German equities$$,
   $$This fund replicates the DAX, the index of the 40 largest German companies.$$,
   $$Volkswagen, SAP, Siemens: Europe's industrial engine in a single share.$$),
  ('ETFAGRI', $$ETF · Agriculture$$,
   $$This fund brings together companies active in seeds, farm equipment and food.$$,
   $$Feeding a growing world population remains one of the steadiest needs there is.$$),
  ('BRKB', $$Holding · Insurance$$,
   $$Berkshire Hathaway is one of the largest listed American companies, in the holding · insurance sector.$$,
   $$Berkshire Hathaway is a stock closely followed by investors: one way to give your portfolio exposure to the holding sector.$$),
  ('JPM', $$Banking$$,
   $$JPMorgan Chase is one of the largest listed American companies, in the banking sector.$$,
   $$JPMorgan Chase is a stock closely followed by investors: one way to give your portfolio exposure to the banking sector.$$),
  ('V', $$Payments$$,
   $$Visa is one of the largest listed American companies, in the payments sector.$$,
   $$Visa is a stock closely followed by investors: one way to give your portfolio exposure to the payments sector.$$),
  ('MA', $$Payments$$,
   $$Mastercard is one of the largest listed American companies, in the payments sector.$$,
   $$Mastercard is a stock closely followed by investors: one way to give your portfolio exposure to the payments sector.$$),
  ('BAC', $$Banking$$,
   $$Bank of America is one of the largest listed American companies, in the banking sector.$$,
   $$Bank of America is a stock closely followed by investors: one way to give your portfolio exposure to the banking sector.$$),
  ('WFC', $$Banking$$,
   $$Wells Fargo is one of the largest listed American companies, in the banking sector.$$,
   $$Wells Fargo is a stock closely followed by investors: one way to give your portfolio exposure to the banking sector.$$)
) as t(symbol, sector_en, description_en, hercule_note_en)
where s.symbol = t.symbol;
