-- =====================================================================
-- Les 500 sociétés du S&P 500.
--
-- Fichier GÉNÉRÉ par tools/build_sp500_seed.py — ne pas éditer à la
-- main. Composition et secteurs : Wikipédia. Place de cotation et
-- devise : EODHD. Logos : Wikimedia Commons (domaine public ou marque
-- déposée) ou EODHD.
--
-- Rejouable : les fiches déjà rédigées ne sont pas écrasées, seul leur
-- logo est complété.
-- =====================================================================

insert into public.securities
  (symbol, eodhd_symbol, currency, asset_type, name, country_code, country,
   sector, sector_en, sector_group, region, initials, logo_url)
values
  ('MMM', 'MMM.US', 'USD', 'stock', '3M', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', '3M', 'https://eodhd.com/img/logos/US/mmm.png'),
  ('AOS', 'AOS.US', 'USD', 'stock', 'A. O. Smith', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'AO', 'https://eodhd.com/img/logos/US/aos.png'),
  ('ABT', 'ABT.US', 'USD', 'stock', 'Abbott Laboratories', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'AB', 'https://commons.wikimedia.org/wiki/Special:FilePath/Abbott_Laboratories_2025_logo.svg?width=160'),
  ('ABBV', 'ABBV.US', 'USD', 'stock', 'AbbVie', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'AB', 'https://eodhd.com/img/logos/US/abbv.png'),
  ('ACN', 'ACN.US', 'USD', 'stock', 'Accenture', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'AC', 'https://eodhd.com/img/logos/US/acn.png'),
  ('ADBE', 'ADBE.US', 'USD', 'stock', 'Adobe Inc.', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'AD', null),
  ('AMD', 'AMD.US', 'USD', 'stock', 'Advanced Micro Devices', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'AD', 'https://commons.wikimedia.org/wiki/Special:FilePath/AMD_Logo.svg?width=160'),
  ('AES', 'AES.US', 'USD', 'stock', 'AES Corporation', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'AE', 'https://commons.wikimedia.org/wiki/Special:FilePath/AES_Corporation_logo.svg?width=160'),
  ('AFL', 'AFL.US', 'USD', 'stock', 'Aflac', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'AF', null),
  ('A', 'A.US', 'USD', 'stock', 'Agilent Technologies', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'AG', 'https://eodhd.com/img/logos/US/a.png'),
  ('APD', 'APD.US', 'USD', 'stock', 'Air Products', 'US', 'États-Unis', 'Matériaux', 'Materials', 'materials', 'us', 'AI', 'https://eodhd.com/img/logos/US/apd.png'),
  ('ABNB', 'ABNB.US', 'USD', 'stock', 'Airbnb', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'AI', 'https://commons.wikimedia.org/wiki/Special:FilePath/Airbnb_Logo_B%C3%A9lo.svg?width=160'),
  ('AKAM', 'AKAM.US', 'USD', 'stock', 'Akamai Technologies', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'AK', 'https://eodhd.com/img/logos/US/akam.png'),
  ('ALB', 'ALB.US', 'USD', 'stock', 'Albemarle Corporation', 'US', 'États-Unis', 'Matériaux', 'Materials', 'materials', 'us', 'AL', 'https://commons.wikimedia.org/wiki/Special:FilePath/Albermarle_Corporation.svg?width=160'),
  ('ARE', 'ARE.US', 'USD', 'stock', 'Alexandria Real Estate Equities', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'AL', null),
  ('ALGN', 'ALGN.US', 'USD', 'stock', 'Align Technology', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'AL', 'https://commons.wikimedia.org/wiki/Special:FilePath/Align_Technology_logo.svg?width=160'),
  ('ALLE', 'ALLE.US', 'USD', 'stock', 'Allegion', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'AL', 'https://eodhd.com/img/logos/US/alle.png'),
  ('LNT', 'LNT.US', 'USD', 'stock', 'Alliant Energy', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'AL', 'https://commons.wikimedia.org/wiki/Special:FilePath/Alliant_Energy_logo.svg?width=160'),
  ('ALL', 'ALL.US', 'USD', 'stock', 'Allstate', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'AL', 'https://eodhd.com/img/logos/US/all.png'),
  ('MO', 'MO.US', 'USD', 'stock', 'Altria', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'AL', 'https://eodhd.com/img/logos/US/mo.png'),
  ('AMCR', 'AMCR.US', 'USD', 'stock', 'Amcor', 'US', 'États-Unis', 'Matériaux', 'Materials', 'materials', 'us', 'AM', 'https://commons.wikimedia.org/wiki/Special:FilePath/Amcor-Logo.svg?width=160'),
  ('AEE', 'AEE.US', 'USD', 'stock', 'Ameren', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'AM', 'https://eodhd.com/img/logos/US/aee.png'),
  ('AEP', 'AEP.US', 'USD', 'stock', 'American Electric Power', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'AM', 'https://eodhd.com/img/logos/US/aep.png'),
  ('AXP', 'AXP.US', 'USD', 'stock', 'American Express', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'AM', 'https://eodhd.com/img/logos/US/axp.png'),
  ('AIG', 'AIG.US', 'USD', 'stock', 'American International Group', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'AM', 'https://eodhd.com/img/logos/US/aig.png'),
  ('AMT', 'AMT.US', 'USD', 'stock', 'American Tower', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'AM', 'https://eodhd.com/img/logos/US/amt.png'),
  ('AWK', 'AWK.US', 'USD', 'stock', 'American Water Works', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'AM', 'https://eodhd.com/img/logos/US/awk.png'),
  ('AMP', 'AMP.US', 'USD', 'stock', 'Ameriprise Financial', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'AM', 'https://eodhd.com/img/logos/US/amp.png'),
  ('AME', 'AME.US', 'USD', 'stock', 'Ametek', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'AM', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ametek-Logo.svg?width=160'),
  ('AMGN', 'AMGN.US', 'USD', 'stock', 'Amgen', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'AM', 'https://commons.wikimedia.org/wiki/Special:FilePath/Amgen.svg?width=160'),
  ('APH', 'APH.US', 'USD', 'stock', 'Amphenol', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'AM', 'https://eodhd.com/img/logos/US/aph.png'),
  ('ADI', 'ADI.US', 'USD', 'stock', 'Analog Devices', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'AN', 'https://eodhd.com/img/logos/US/adi.png'),
  ('AON', 'AON.US', 'USD', 'stock', 'Aon plc', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'AO', 'https://eodhd.com/img/logos/US/aon.png'),
  ('APA', 'APA.US', 'USD', 'stock', 'APA Corporation', 'US', 'États-Unis', 'Énergie-pétrole', 'Energy and oil', 'energy', 'us', 'AP', 'https://commons.wikimedia.org/wiki/Special:FilePath/Apache_Corporation_Logo.svg?width=160'),
  ('APO', 'APO.US', 'USD', 'stock', 'Apollo Global Management', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'AP', 'https://commons.wikimedia.org/wiki/Special:FilePath/Apollo_Global_Management_logo.svg?width=160'),
  ('AMAT', 'AMAT.US', 'USD', 'stock', 'Applied Materials', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'AP', 'https://eodhd.com/img/logos/US/amat.png'),
  ('APP', 'APP.US', 'USD', 'stock', 'AppLovin', 'US', 'États-Unis', 'Communication-médias', 'Communication services', 'telecom', 'us', 'AP', null),
  ('APTV', 'APTV.US', 'USD', 'stock', 'Aptiv', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'auto', 'us', 'AP', 'https://commons.wikimedia.org/wiki/Special:FilePath/Delphi.svg?width=160'),
  ('ACGL', 'ACGL.US', 'USD', 'stock', 'Arch Capital Group', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'AR', 'https://eodhd.com/img/logos/US/acgl.png'),
  ('ADM', 'ADM.US', 'USD', 'stock', 'Archer Daniels Midland', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'AR', 'https://eodhd.com/img/logos/US/adm.png'),
  ('ARES', 'ARES.US', 'USD', 'stock', 'Ares Management', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'AR', null),
  ('ANET', 'ANET.US', 'USD', 'stock', 'Arista Networks', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'AR', 'https://commons.wikimedia.org/wiki/Special:FilePath/Arista-networks-logo.svg?width=160'),
  ('AJG', 'AJG.US', 'USD', 'stock', 'Arthur J. Gallagher & Co.', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'AR', null),
  ('AIZ', 'AIZ.US', 'USD', 'stock', 'Assurant', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'AS', null),
  ('T', 'T.US', 'USD', 'stock', 'AT&T', 'US', 'États-Unis', 'Communication-médias', 'Communication services', 'telecom', 'us', 'AT', 'https://eodhd.com/img/logos/US/t.png'),
  ('ATO', 'ATO.US', 'USD', 'stock', 'Atmos Energy', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'AT', 'https://commons.wikimedia.org/wiki/Special:FilePath/Atmos_Energy_Logo.svg?width=160'),
  ('ADSK', 'ADSK.US', 'USD', 'stock', 'Autodesk', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'AU', 'https://eodhd.com/img/logos/US/adsk.png'),
  ('ADP', 'ADP.US', 'USD', 'stock', 'Automatic Data Processing', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'AU', 'https://eodhd.com/img/logos/US/adp.png'),
  ('AZO', 'AZO.US', 'USD', 'stock', 'AutoZone', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'auto', 'us', 'AU', 'https://commons.wikimedia.org/wiki/Special:FilePath/Logo_of_AutoZone.png?width=160'),
  ('AVY', 'AVY.US', 'USD', 'stock', 'Avery Dennison', 'US', 'États-Unis', 'Matériaux', 'Materials', 'materials', 'us', 'AV', 'https://commons.wikimedia.org/wiki/Special:FilePath/Avery_Dennison_logo_red.svg?width=160'),
  ('AXON', 'AXON.US', 'USD', 'stock', 'Axon Enterprise', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'AX', 'https://commons.wikimedia.org/wiki/Special:FilePath/AXON_Company_logo.svg?width=160'),
  ('BKR', 'BKR.US', 'USD', 'stock', 'Baker Hughes', 'US', 'États-Unis', 'Énergie-pétrole', 'Energy and oil', 'energy', 'us', 'BA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Baker_Hughes_logo.svg?width=160'),
  ('BALL', 'BALL.US', 'USD', 'stock', 'Ball Corporation', 'US', 'États-Unis', 'Matériaux', 'Materials', 'materials', 'us', 'BA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ball_Corporation_logo_2024.svg?width=160'),
  ('BAX', 'BAX.US', 'USD', 'stock', 'Baxter International', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'BA', 'https://eodhd.com/img/logos/US/bax.png'),
  ('BDX', 'BDX.US', 'USD', 'stock', 'Becton Dickinson', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'BE', 'https://commons.wikimedia.org/wiki/Special:FilePath/BD_%28company%29_logo.svg?width=160'),
  ('BBY', 'BBY.US', 'USD', 'stock', 'Best Buy', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'BE', null),
  ('TECH', 'TECH.US', 'USD', 'stock', 'Bio-Techne', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'BI', 'https://eodhd.com/img/logos/US/tech.png'),
  ('BIIB', 'BIIB.US', 'USD', 'stock', 'Biogen', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'BI', null),
  ('BLK', 'BLK.US', 'USD', 'stock', 'BlackRock', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'BL', 'https://eodhd.com/img/logos/US/blk.png'),
  ('BX', 'BX.US', 'USD', 'stock', 'Blackstone Inc.', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'BL', 'https://commons.wikimedia.org/wiki/Special:FilePath/The_Blackstone_Group_logo_%282%29.svg?width=160'),
  ('XYZ', 'XYZ.US', 'USD', 'stock', 'Block, Inc.', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'BL', 'https://commons.wikimedia.org/wiki/Special:FilePath/Square%2C_Inc._logo.svg?width=160'),
  ('BE', 'BE.US', 'USD', 'stock', 'Bloom Energy', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'BL', 'https://commons.wikimedia.org/wiki/Special:FilePath/Bloom_Energy_logo.svg?width=160'),
  ('BNY', 'BNY.US', 'USD', 'stock', 'BNY Mellon', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'BN', 'https://commons.wikimedia.org/wiki/Special:FilePath/BNY_Mellon.svg?width=160'),
  ('BA', 'BA.US', 'USD', 'stock', 'Boeing', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'BO', 'https://eodhd.com/img/logos/US/ba.png'),
  ('BKNG', 'BKNG.US', 'USD', 'stock', 'Booking Holdings', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'BO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Logo_of_Booking_Holdings_Inc%2C%28lock_up%2C_stacked_with_Brands%2C_full_color%29.PNG?width=160'),
  ('BSX', 'BSX.US', 'USD', 'stock', 'Boston Scientific', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'BO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Boston_Scientific_Logo.svg?width=160'),
  ('BMY', 'BMY.US', 'USD', 'stock', 'Bristol Myers Squibb', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'BR', 'https://eodhd.com/img/logos/US/bmy.png'),
  ('AVGO', 'AVGO.US', 'USD', 'stock', 'Broadcom', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'BR', 'https://eodhd.com/img/logos/US/avgo.png'),
  ('BR', 'BR.US', 'USD', 'stock', 'Broadridge Financial Solutions', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'BR', 'https://eodhd.com/img/logos/US/br.png'),
  ('BRO', 'BRO.US', 'USD', 'stock', 'Brown & Brown', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'BR', null),
  ('BFB', 'BF-B.US', 'USD', 'stock', 'Brown–Forman', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'BR', null),
  ('BG', 'BG.US', 'USD', 'stock', 'Bunge Global', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'BU', 'https://commons.wikimedia.org/wiki/Special:FilePath/Bunge_Limited_Logo.svg?width=160'),
  ('BXP', 'BXP.US', 'USD', 'stock', 'BXP, Inc.', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'BX', 'https://eodhd.com/img/logos/US/bxp.png'),
  ('CHRW', 'CHRW.US', 'USD', 'stock', 'C.H. Robinson', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'CH', 'https://commons.wikimedia.org/wiki/Special:FilePath/C._H._Robinson_logo.svg?width=160'),
  ('CDNS', 'CDNS.US', 'USD', 'stock', 'Cadence Design Systems', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'CA', 'https://eodhd.com/img/logos/US/cdns.png'),
  ('CPT', 'CPT.US', 'USD', 'stock', 'Camden Property Trust', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'CA', null),
  ('COF', 'COF.US', 'USD', 'stock', 'Capital One', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'CA', 'https://eodhd.com/img/logos/US/cof.png'),
  ('CAH', 'CAH.US', 'USD', 'stock', 'Cardinal Health', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'CA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Cardinal_Health_Logo.svg?width=160'),
  ('CCL', 'CCL.US', 'USD', 'stock', 'Carnival Corporation', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'CA', 'https://eodhd.com/img/logos/US/ccl.png'),
  ('CARR.US', 'CARR.US', 'USD', 'stock', 'Carrier Global', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'CA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Logo_of_the_Carrier_Corporation.svg?width=160'),
  ('CVNA', 'CVNA.US', 'USD', 'stock', 'Carvana', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'auto', 'us', 'CA', null),
  ('CASY', 'CASY.US', 'USD', 'stock', 'Casey''s', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'CA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Casey%27s_logo.svg?width=160'),
  ('CAT', 'CAT.US', 'USD', 'stock', 'Caterpillar Inc.', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'CA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Caterpillar_logo.svg?width=160'),
  ('CBRE', 'CBRE.US', 'USD', 'stock', 'CBRE Group', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'CB', null),
  ('CDW', 'CDW.US', 'USD', 'stock', 'CDW Corporation', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'CD', 'https://commons.wikimedia.org/wiki/Special:FilePath/CDW_Logo.svg?width=160'),
  ('COR', 'COR.US', 'USD', 'stock', 'Cencora', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'CE', 'https://commons.wikimedia.org/wiki/Special:FilePath/Cencora_logo.png?width=160'),
  ('CNC', 'CNC.US', 'USD', 'stock', 'Centene Corporation', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'CE', 'https://commons.wikimedia.org/wiki/Special:FilePath/Centene_Corporation_Logo.svg?width=160'),
  ('CNP', 'CNP.US', 'USD', 'stock', 'CenterPoint Energy', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'CE', 'https://commons.wikimedia.org/wiki/Special:FilePath/CenterPoint_Energy_logo.svg?width=160'),
  ('CF', 'CF.US', 'USD', 'stock', 'CF Industries', 'US', 'États-Unis', 'Matériaux', 'Materials', 'materials', 'us', 'CF', 'https://eodhd.com/img/logos/US/cf.png'),
  ('CRL', 'CRL.US', 'USD', 'stock', 'Charles River Laboratories', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'CH', 'https://commons.wikimedia.org/wiki/Special:FilePath/Charles_River_Laboratories_Logo.svg?width=160'),
  ('SCHW', 'SCHW.US', 'USD', 'stock', 'Charles Schwab Corporation', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'CH', 'https://eodhd.com/img/logos/US/schw.png'),
  ('CHTR', 'CHTR.US', 'USD', 'stock', 'Charter Communications', 'US', 'États-Unis', 'Communication-médias', 'Communication services', 'telecom', 'us', 'CH', 'https://commons.wikimedia.org/wiki/Special:FilePath/Charter_Communications_Logo.svg?width=160'),
  ('CVX', 'CVX.US', 'USD', 'stock', 'Chevron Corporation', 'US', 'États-Unis', 'Énergie-pétrole', 'Energy and oil', 'energy', 'us', 'CH', 'https://eodhd.com/img/logos/US/cvx.png'),
  ('CMG', 'CMG.US', 'USD', 'stock', 'Chipotle Mexican Grill', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'CH', null),
  ('CB', 'CB.US', 'USD', 'stock', 'Chubb Limited', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'CH', 'https://eodhd.com/img/logos/US/cb.png'),
  ('CHD', 'CHD.US', 'USD', 'stock', 'Church & Dwight', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'CH', 'https://eodhd.com/img/logos/US/chd.png'),
  ('CIEN', 'CIEN.US', 'USD', 'stock', 'Ciena', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'CI', 'https://eodhd.com/img/logos/US/cien.png'),
  ('CI', 'CI.US', 'USD', 'stock', 'Cigna', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'CI', 'https://eodhd.com/img/logos/US/ci.png'),
  ('CINF', 'CINF.US', 'USD', 'stock', 'Cincinnati Financial', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'CI', 'https://eodhd.com/img/logos/US/cinf.png'),
  ('CTAS', 'CTAS.US', 'USD', 'stock', 'Cintas', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'CI', 'https://commons.wikimedia.org/wiki/Special:FilePath/Cintas-Logo.SVG?width=160'),
  ('CSCO', 'CSCO.US', 'USD', 'stock', 'Cisco', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'CI', 'https://commons.wikimedia.org/wiki/Special:FilePath/Cisco_logo.svg?width=160'),
  ('C', 'C.US', 'USD', 'stock', 'Citigroup', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'CI', 'https://eodhd.com/img/logos/US/c.png'),
  ('CFG', 'CFG.US', 'USD', 'stock', 'Citizens Financial Group', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'CI', 'https://commons.wikimedia.org/wiki/Special:FilePath/Citizens_Financial_Group_logo.svg?width=160'),
  ('CLX', 'CLX.US', 'USD', 'stock', 'Clorox', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'CL', 'https://commons.wikimedia.org/wiki/Special:FilePath/The_Clorox_Company_logo.svg?width=160'),
  ('CME', 'CME.US', 'USD', 'stock', 'CME Group', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'CM', 'https://eodhd.com/img/logos/US/cme.png'),
  ('CMS', 'CMS.US', 'USD', 'stock', 'CMS Energy', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'CM', null),
  ('KO', 'KO.US', 'USD', 'stock', 'Coca-Cola Company (The)', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'CO', 'https://eodhd.com/img/logos/US/ko.png'),
  ('CTSH', 'CTSH.US', 'USD', 'stock', 'Cognizant', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'CO', null),
  ('COHR', 'COHR.US', 'USD', 'stock', 'Coherent Corp.', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'CO', null),
  ('COIN', 'COIN.US', 'USD', 'stock', 'Coinbase', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'CO', 'https://eodhd.com/img/logos/US/coin.png'),
  ('CL', 'CL.US', 'USD', 'stock', 'Colgate-Palmolive', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'CO', 'https://eodhd.com/img/logos/US/cl.png'),
  ('CMCSA', 'CMCSA.US', 'USD', 'stock', 'Comcast', 'US', 'États-Unis', 'Communication-médias', 'Communication services', 'telecom', 'us', 'CO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Comcast.svg?width=160'),
  ('FIX', 'FIX.US', 'USD', 'stock', 'Comfort Systems USA', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'CO', null),
  ('COP', 'COP.US', 'USD', 'stock', 'ConocoPhillips', 'US', 'États-Unis', 'Énergie-pétrole', 'Energy and oil', 'energy', 'us', 'CO', 'https://commons.wikimedia.org/wiki/Special:FilePath/ConocoPhillips_Logo.svg?width=160'),
  ('ED', 'ED.US', 'USD', 'stock', 'Consolidated Edison', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'CO', 'https://eodhd.com/img/logos/US/ed.png'),
  ('STZ', 'STZ.US', 'USD', 'stock', 'Constellation Brands', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'CO', null),
  ('CEG', 'CEG.US', 'USD', 'stock', 'Constellation Energy', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'CO', null),
  ('COO', 'COO.US', 'USD', 'stock', 'Cooper Companies (The)', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'CO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Cooper_companies_logo.png?width=160'),
  ('CPRT', 'CPRT.US', 'USD', 'stock', 'Copart', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'CO', null),
  ('GLW', 'GLW.US', 'USD', 'stock', 'Corning Inc.', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'CO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Corning_Incorporated_Logo.svg?width=160'),
  ('CPAY', 'CPAY.US', 'USD', 'stock', 'Corpay', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'CO', null),
  ('CTVA', 'CTVA.US', 'USD', 'stock', 'Corteva', 'US', 'États-Unis', 'Matériaux', 'Materials', 'materials', 'us', 'CO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Corteva_logo.svg?width=160'),
  ('CSGP', 'CSGP.US', 'USD', 'stock', 'CoStar Group', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'CO', 'https://commons.wikimedia.org/wiki/Special:FilePath/CoStar_Group_logo.svg?width=160'),
  ('COST', 'COST.US', 'USD', 'stock', 'Costco', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'CO', 'https://eodhd.com/img/logos/US/cost.png'),
  ('CRH', 'CRH.US', 'USD', 'stock', 'CRH plc', 'US', 'États-Unis', 'Matériaux', 'Materials', 'materials', 'us', 'CR', 'https://commons.wikimedia.org/wiki/Special:FilePath/CRH_Logo.svg?width=160'),
  ('CRWD', 'CRWD.US', 'USD', 'stock', 'CrowdStrike', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'CR', 'https://commons.wikimedia.org/wiki/Special:FilePath/CrowdStrike_logo.svg?width=160'),
  ('CCI', 'CCI.US', 'USD', 'stock', 'Crown Castle', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'CR', 'https://eodhd.com/img/logos/US/cci.png'),
  ('CSX', 'CSX.US', 'USD', 'stock', 'CSX Corporation', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'CS', 'https://commons.wikimedia.org/wiki/Special:FilePath/CSX_transp_logo.svg?width=160'),
  ('CMI', 'CMI.US', 'USD', 'stock', 'Cummins', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'CU', 'https://commons.wikimedia.org/wiki/Special:FilePath/Cummins_logo.svg?width=160'),
  ('CVS', 'CVS.US', 'USD', 'stock', 'CVS Health', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'CV', 'https://eodhd.com/img/logos/US/cvs.png'),
  ('DHR', 'DHR.US', 'USD', 'stock', 'Danaher Corporation', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'DA', 'https://eodhd.com/img/logos/US/dhr.png'),
  ('DRI', 'DRI.US', 'USD', 'stock', 'Darden Restaurants', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'DA', null),
  ('DDOG', 'DDOG.US', 'USD', 'stock', 'Datadog', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'DA', null),
  ('DVA', 'DVA.US', 'USD', 'stock', 'DaVita', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'DA', 'https://commons.wikimedia.org/wiki/Special:FilePath/DaVita_logo.svg?width=160'),
  ('DECK', 'DECK.US', 'USD', 'stock', 'Deckers Brands', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'DE', 'https://commons.wikimedia.org/wiki/Special:FilePath/Deckers_Brands_logo.png?width=160'),
  ('DE', 'DE.US', 'USD', 'stock', 'Deere & Company', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'DE', 'https://commons.wikimedia.org/wiki/Special:FilePath/John_Deere_text_only.png?width=160'),
  ('DELL', 'DELL.US', 'USD', 'stock', 'Dell Technologies', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'DE', 'https://commons.wikimedia.org/wiki/Special:FilePath/Dell_Technologies_logo.svg?width=160'),
  ('DAL', 'DAL.US', 'USD', 'stock', 'Delta Air Lines', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'DE', 'https://eodhd.com/img/logos/US/dal.png'),
  ('DVN', 'DVN.US', 'USD', 'stock', 'Devon Energy', 'US', 'États-Unis', 'Énergie-pétrole', 'Energy and oil', 'energy', 'us', 'DE', 'https://eodhd.com/img/logos/US/dvn.png'),
  ('DXCM', 'DXCM.US', 'USD', 'stock', 'Dexcom', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'DE', null),
  ('FANG', 'FANG.US', 'USD', 'stock', 'Diamondback Energy', 'US', 'États-Unis', 'Énergie-pétrole', 'Energy and oil', 'energy', 'us', 'DI', 'https://eodhd.com/img/logos/US/fang.png'),
  ('DLR', 'DLR.US', 'USD', 'stock', 'Digital Realty', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'DI', 'https://eodhd.com/img/logos/US/dlr.png'),
  ('DG.US', 'DG.US', 'USD', 'stock', 'Dollar General', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'DO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Dollar_General_logo.svg?width=160'),
  ('DLTR', 'DLTR.US', 'USD', 'stock', 'Dollar Tree', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'DO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Dollar_Tree_logo.svg?width=160'),
  ('D', 'D.US', 'USD', 'stock', 'Dominion Energy', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'DO', 'https://eodhd.com/img/logos/US/d.png'),
  ('DPZ', 'DPZ.US', 'USD', 'stock', 'Domino''s', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'DO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Domino%27s_2025.svg?width=160'),
  ('DASH', 'DASH.US', 'USD', 'stock', 'DoorDash', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'DO', 'https://commons.wikimedia.org/wiki/Special:FilePath/DoorDash_Logo.svg?width=160'),
  ('DOV', 'DOV.US', 'USD', 'stock', 'Dover Corporation', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'DO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Dover_Corporation_logo.png?width=160'),
  ('DOW', 'DOW.US', 'USD', 'stock', 'Dow Inc.', 'US', 'États-Unis', 'Matériaux', 'Materials', 'materials', 'us', 'DO', 'https://eodhd.com/img/logos/US/dow.png'),
  ('DHI', 'DHI.US', 'USD', 'stock', 'D. R. Horton', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'DR', 'https://commons.wikimedia.org/wiki/Special:FilePath/D._R._Horton_logo.svg?width=160'),
  ('DTE', 'DTE.US', 'USD', 'stock', 'DTE Energy', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'DT', 'https://eodhd.com/img/logos/US/dte.png'),
  ('DUK', 'DUK.US', 'USD', 'stock', 'Duke Energy', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'DU', 'https://commons.wikimedia.org/wiki/Special:FilePath/Duke_Energy_logo.svg?width=160'),
  ('DD', 'DD.US', 'USD', 'stock', 'DuPont', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'DU', 'https://eodhd.com/img/logos/US/dd.png'),
  ('ETN', 'ETN.US', 'USD', 'stock', 'Eaton Corporation', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'EA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Eaton_Corporation_Logo.svg?width=160'),
  ('EBAY', 'EBAY.US', 'USD', 'stock', 'eBay Inc.', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'EB', 'https://eodhd.com/img/logos/US/ebay.png'),
  ('ECHO', 'ECHO.US', 'USD', 'stock', 'EchoStar', 'US', 'États-Unis', 'Communication-médias', 'Communication services', 'telecom', 'us', 'EC', 'https://commons.wikimedia.org/wiki/Special:FilePath/EchoStar_logo.svg?width=160'),
  ('ECL', 'ECL.US', 'USD', 'stock', 'Ecolab', 'US', 'États-Unis', 'Matériaux', 'Materials', 'materials', 'us', 'EC', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ecolab.svg?width=160'),
  ('EIX', 'EIX.US', 'USD', 'stock', 'Edison International', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'ED', 'https://eodhd.com/img/logos/US/eix.png'),
  ('EW', 'EW.US', 'USD', 'stock', 'Edwards Lifesciences', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'ED', 'https://commons.wikimedia.org/wiki/Special:FilePath/Edwards_Lifesciences.svg?width=160'),
  ('ELV', 'ELV.US', 'USD', 'stock', 'Elevance Health', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'EL', 'https://commons.wikimedia.org/wiki/Special:FilePath/WellPoint_logo.svg?width=160'),
  ('EME', 'EME.US', 'USD', 'stock', 'Emcor', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'EM', null),
  ('EMR', 'EMR.US', 'USD', 'stock', 'Emerson Electric', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'EM', null),
  ('ETR', 'ETR.US', 'USD', 'stock', 'Entergy', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'EN', null),
  ('EOG', 'EOG.US', 'USD', 'stock', 'EOG Resources', 'US', 'États-Unis', 'Énergie-pétrole', 'Energy and oil', 'energy', 'us', 'EO', 'https://eodhd.com/img/logos/US/eog.png'),
  ('EQT', 'EQT.US', 'USD', 'stock', 'EQT Corporation', 'US', 'États-Unis', 'Énergie-pétrole', 'Energy and oil', 'energy', 'us', 'EQ', null),
  ('EFX.US', 'EFX.US', 'USD', 'stock', 'Equifax', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'EQ', 'https://eodhd.com/img/logos/US/efx.png'),
  ('EQIX', 'EQIX.US', 'USD', 'stock', 'Equinix', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'EQ', 'https://eodhd.com/img/logos/US/eqix.png'),
  ('ERIE', 'ERIE.US', 'USD', 'stock', 'Erie Indemnity', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'ER', null),
  ('ESS', 'ESS.US', 'USD', 'stock', 'Essex Property Trust', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'ES', 'https://eodhd.com/img/logos/US/ess.png'),
  ('EL', 'EL.US', 'USD', 'stock', 'Estée Lauder Companies (The)', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'ES', 'https://commons.wikimedia.org/wiki/Special:FilePath/Est%C3%A9e_Lauder_Companies_logo.svg?width=160'),
  ('EG', 'EG.US', 'USD', 'stock', 'Everest Group', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'EV', null),
  ('EVRG', 'EVRG.US', 'USD', 'stock', 'Evergy', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'EV', 'https://commons.wikimedia.org/wiki/Special:FilePath/Evergy_logo.svg?width=160'),
  ('P', 'P.US', 'USD', 'stock', 'Everpure', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'EV', 'https://eodhd.com/img/logos/US/p.png'),
  ('ES', 'ES.US', 'USD', 'stock', 'Eversource Energy', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'EV', 'https://eodhd.com/img/logos/US/es.png'),
  ('EXC', 'EXC.US', 'USD', 'stock', 'Exelon', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'EX', 'https://eodhd.com/img/logos/US/exc.png'),
  ('EXE', 'EXE.US', 'USD', 'stock', 'Expand Energy', 'US', 'États-Unis', 'Énergie-pétrole', 'Energy and oil', 'energy', 'us', 'EX', 'https://commons.wikimedia.org/wiki/Special:FilePath/Chesapeake_Energy_logo.svg?width=160'),
  ('EXPE', 'EXPE.US', 'USD', 'stock', 'Expedia Group', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'EX', 'https://commons.wikimedia.org/wiki/Special:FilePath/Expedia_Inc._logo.svg?width=160'),
  ('EXPD', 'EXPD.US', 'USD', 'stock', 'Expeditors International', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'EX', 'https://commons.wikimedia.org/wiki/Special:FilePath/Expeditors_logo.svg?width=160'),
  ('EXR', 'EXR.US', 'USD', 'stock', 'Extra Space Storage', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'EX', 'https://eodhd.com/img/logos/US/exr.png'),
  ('XOM', 'XOM.US', 'USD', 'stock', 'ExxonMobil', 'US', 'États-Unis', 'Énergie-pétrole', 'Energy and oil', 'energy', 'us', 'EX', 'https://commons.wikimedia.org/wiki/Special:FilePath/Exxon_Mobil_Logo.svg?width=160'),
  ('FFIV', 'FFIV.US', 'USD', 'stock', 'F5, Inc.', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'F5', null),
  ('FDS', 'FDS.US', 'USD', 'stock', 'FactSet', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'FA', 'https://commons.wikimedia.org/wiki/Special:FilePath/FactSet_wordmark.svg?width=160'),
  ('FICO', 'FICO.US', 'USD', 'stock', 'Fair Isaac', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'FA', null),
  ('FAST', 'FAST.US', 'USD', 'stock', 'Fastenal', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'FA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Fastenal_logo.svg?width=160'),
  ('FRT', 'FRT.US', 'USD', 'stock', 'Federal Realty Investment Trust', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'FE', 'https://eodhd.com/img/logos/US/frt.png'),
  ('FDX', 'FDX.US', 'USD', 'stock', 'FedEx', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'FE', null),
  ('FDXF', 'FDXF.US', 'USD', 'stock', 'FedEx Freight', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'FE', null),
  ('FERG', 'FERG.US', 'USD', 'stock', 'Ferguson Enterprises', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'FE', null),
  ('FIS', 'FIS.US', 'USD', 'stock', 'Fidelity National Information Services', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'FI', 'https://eodhd.com/img/logos/US/fis.png'),
  ('FITB', 'FITB.US', 'USD', 'stock', 'Fifth Third Bancorp', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'FI', 'https://eodhd.com/img/logos/US/fitb.png'),
  ('FSLR', 'FSLR.US', 'USD', 'stock', 'First Solar', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'FI', 'https://eodhd.com/img/logos/US/fslr.png'),
  ('FE', 'FE.US', 'USD', 'stock', 'FirstEnergy', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'FI', 'https://eodhd.com/img/logos/US/fe.png'),
  ('FISV', 'FISV.US', 'USD', 'stock', 'Fiserv', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'FI', 'https://commons.wikimedia.org/wiki/Special:FilePath/Fiserv_Logo.svg?width=160'),
  ('FLEX', 'FLEX.US', 'USD', 'stock', 'Flex Ltd.', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'FL', null),
  ('F', 'F.US', 'USD', 'stock', 'Ford Motor Company', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'auto', 'us', 'FO', 'https://eodhd.com/img/logos/US/f.png'),
  ('FTNT', 'FTNT.US', 'USD', 'stock', 'Fortinet', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'FO', 'https://eodhd.com/img/logos/US/ftnt.png'),
  ('FTV', 'FTV.US', 'USD', 'stock', 'Fortive', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'FO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Fortive_Logo.svg?width=160'),
  ('FOXA', 'FOXA.US', 'USD', 'stock', 'Fox Corporation', 'US', 'États-Unis', 'Communication-médias', 'Communication services', 'telecom', 'us', 'FO', 'https://eodhd.com/img/logos/US/foxa.png'),
  ('FOX', 'FOX.US', 'USD', 'stock', 'Fox Corporation', 'US', 'États-Unis', 'Communication-médias', 'Communication services', 'telecom', 'us', 'FO', 'https://eodhd.com/img/logos/US/fox.png'),
  ('BEN', 'BEN.US', 'USD', 'stock', 'Franklin Resources', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'FR', 'https://eodhd.com/img/logos/US/ben.png'),
  ('FCX', 'FCX.US', 'USD', 'stock', 'Freeport-McMoRan', 'US', 'États-Unis', 'Matériaux', 'Materials', 'materials', 'us', 'FR', 'https://eodhd.com/img/logos/US/fcx.png'),
  ('GRMN', 'GRMN.US', 'USD', 'stock', 'Garmin', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'GA', 'https://eodhd.com/img/logos/US/grmn.png'),
  ('IT', 'IT.US', 'USD', 'stock', 'Gartner', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'GA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Gartner_logo.svg?width=160'),
  ('GE', 'GE.US', 'USD', 'stock', 'GE Aerospace', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'GE', 'https://eodhd.com/img/logos/US/ge.png'),
  ('GEHC', 'GEHC.US', 'USD', 'stock', 'GE HealthCare', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'GE', 'https://commons.wikimedia.org/wiki/Special:FilePath/GE_HealthCare_logo_2023.svg?width=160'),
  ('GEV', 'GEV.US', 'USD', 'stock', 'GE Vernova', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'GE', 'https://commons.wikimedia.org/wiki/Special:FilePath/GE_Vernova_logo.svg?width=160'),
  ('GEN', 'GEN.US', 'USD', 'stock', 'Gen Digital', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'GE', 'https://commons.wikimedia.org/wiki/Special:FilePath/Logo_NortonLifeLock.svg?width=160'),
  ('GNRC', 'GNRC.US', 'USD', 'stock', 'Generac', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'GE', 'https://commons.wikimedia.org/wiki/Special:FilePath/Generac_Power_Systems_logo.png?width=160'),
  ('GD', 'GD.US', 'USD', 'stock', 'General Dynamics', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'GE', 'https://eodhd.com/img/logos/US/gd.png'),
  ('GIS', 'GIS.US', 'USD', 'stock', 'General Mills', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'GE', 'https://commons.wikimedia.org/wiki/Special:FilePath/General_Mills_logo.svg?width=160'),
  ('GM', 'GM.US', 'USD', 'stock', 'General Motors', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'auto', 'us', 'GE', 'https://commons.wikimedia.org/wiki/Special:FilePath/General_motors_logo_with_wordmark.svg?width=160'),
  ('GPC', 'GPC.US', 'USD', 'stock', 'Genuine Parts Company', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'GE', 'https://commons.wikimedia.org/wiki/Special:FilePath/Genuine_Parts_Company_logo.svg?width=160'),
  ('GILD', 'GILD.US', 'USD', 'stock', 'Gilead Sciences', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'GI', null),
  ('GPN', 'GPN.US', 'USD', 'stock', 'Global Payments', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'GL', 'https://commons.wikimedia.org/wiki/Special:FilePath/Global_Payments_Inc._logo.svg?width=160'),
  ('GL', 'GL.US', 'USD', 'stock', 'Globe Life', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'GL', 'https://commons.wikimedia.org/wiki/Special:FilePath/Globe_Life_logo.svg?width=160'),
  ('GDDY', 'GDDY.US', 'USD', 'stock', 'GoDaddy', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'GO', 'https://commons.wikimedia.org/wiki/Special:FilePath/GoDaddy_logo.svg?width=160'),
  ('GS', 'GS.US', 'USD', 'stock', 'Goldman Sachs', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'GO', 'https://eodhd.com/img/logos/US/gs.png'),
  ('HAL', 'HAL.US', 'USD', 'stock', 'Halliburton', 'US', 'États-Unis', 'Énergie-pétrole', 'Energy and oil', 'energy', 'us', 'HA', 'https://eodhd.com/img/logos/US/hal.png'),
  ('HIG', 'HIG.US', 'USD', 'stock', 'Hartford (The)', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'HA', null),
  ('HAS', 'HAS.US', 'USD', 'stock', 'Hasbro', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'HA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Hasbro_logo.svg?width=160'),
  ('HCA', 'HCA.US', 'USD', 'stock', 'HCA Healthcare', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'HC', 'https://eodhd.com/img/logos/US/hca.png'),
  ('DOC', 'DOC.US', 'USD', 'stock', 'Healthpeak Properties', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'HE', null),
  ('HSIC', 'HSIC.US', 'USD', 'stock', 'Henry Schein', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'HE', null),
  ('HSY', 'HSY.US', 'USD', 'stock', 'Hershey Company (The)', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'HE', 'https://commons.wikimedia.org/wiki/Special:FilePath/HersheyCo.svg?width=160'),
  ('HPE', 'HPE.US', 'USD', 'stock', 'Hewlett Packard Enterprise', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'HE', 'https://commons.wikimedia.org/wiki/Special:FilePath/Hewlett_Packard_Enterprise_logo.svg?width=160'),
  ('HLT', 'HLT.US', 'USD', 'stock', 'Hilton Worldwide', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'HI', 'https://commons.wikimedia.org/wiki/Special:FilePath/Hilton_Worldwide_logo.svg?width=160'),
  ('HD', 'HD.US', 'USD', 'stock', 'Home Depot (The)', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'HO', 'https://eodhd.com/img/logos/US/hd.png'),
  ('HONA', 'HONA.US', 'USD', 'stock', 'Honeywell Aerospace', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'HO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Honeywell_The_Power_of_Connected.png?width=160'),
  ('HON', 'HON.US', 'USD', 'stock', 'Honeywell Technologies', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'HO', 'https://eodhd.com/img/logos/US/hon.png'),
  ('HRL', 'HRL.US', 'USD', 'stock', 'Hormel Foods', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'HO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Hormel_Foods_logo.png?width=160'),
  ('HST', 'HST.US', 'USD', 'stock', 'Host Hotels & Resorts', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'HO', 'https://eodhd.com/img/logos/US/hst.png'),
  ('HWM', 'HWM.US', 'USD', 'stock', 'Howmet Aerospace', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'HO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Howmet_Aerospace_logo.svg?width=160'),
  ('HPQ', 'HPQ.US', 'USD', 'stock', 'HP Inc.', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'HP', null),
  ('HUBB', 'HUBB.US', 'USD', 'stock', 'Hubbell Incorporated', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'HU', 'https://commons.wikimedia.org/wiki/Special:FilePath/Hubbell.svg?width=160'),
  ('HUM', 'HUM.US', 'USD', 'stock', 'Humana', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'HU', 'https://commons.wikimedia.org/wiki/Special:FilePath/Humana_logo.svg?width=160'),
  ('HBAN', 'HBAN.US', 'USD', 'stock', 'Huntington Bancshares', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'HU', 'https://eodhd.com/img/logos/US/hban.png'),
  ('HII', 'HII.US', 'USD', 'stock', 'Huntington Ingalls Industries', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'HU', 'https://eodhd.com/img/logos/US/hii.png'),
  ('IBM', 'IBM.US', 'USD', 'stock', 'IBM', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'IB', 'https://commons.wikimedia.org/wiki/Special:FilePath/IBM_logo.svg?width=160'),
  ('IEX', 'IEX.US', 'USD', 'stock', 'IDEX Corporation', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'ID', null),
  ('IDXX', 'IDXX.US', 'USD', 'stock', 'Idexx Laboratories', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'ID', 'https://commons.wikimedia.org/wiki/Special:FilePath/IDEXX_Labs.svg?width=160'),
  ('ITW', 'ITW.US', 'USD', 'stock', 'Illinois Tool Works', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'IL', 'https://commons.wikimedia.org/wiki/Special:FilePath/ITW.svg?width=160'),
  ('ILMN', 'ILMN.US', 'USD', 'stock', 'Illumina, Inc.', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'IL', 'https://commons.wikimedia.org/wiki/Special:FilePath/Illumina_logo.svg?width=160'),
  ('INCY', 'INCY.US', 'USD', 'stock', 'Incyte', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'IN', 'https://commons.wikimedia.org/wiki/Special:FilePath/Incyte_logo.svg?width=160'),
  ('IR', 'IR.US', 'USD', 'stock', 'Ingersoll Rand', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'IN', null),
  ('INTC', 'INTC.US', 'USD', 'stock', 'Intel', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'IN', null),
  ('IBKR', 'IBKR.US', 'USD', 'stock', 'Interactive Brokers', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'IN', null),
  ('ICE', 'ICE.US', 'USD', 'stock', 'Intercontinental Exchange', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'IN', 'https://commons.wikimedia.org/wiki/Special:FilePath/Logo_of_the_IntercontinentalExchange.svg?width=160'),
  ('IFF', 'IFF.US', 'USD', 'stock', 'International Flavors & Fragrances', 'US', 'États-Unis', 'Matériaux', 'Materials', 'materials', 'us', 'IN', 'https://eodhd.com/img/logos/US/iff.png'),
  ('IP', 'IP.US', 'USD', 'stock', 'International Paper', 'US', 'États-Unis', 'Matériaux', 'Materials', 'materials', 'us', 'IN', 'https://eodhd.com/img/logos/US/ip.png'),
  ('INTU', 'INTU.US', 'USD', 'stock', 'Intuit', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'IN', null),
  ('ISRG', 'ISRG.US', 'USD', 'stock', 'Intuitive Surgical', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'IN', 'https://commons.wikimedia.org/wiki/Special:FilePath/Intuitive_Surgical_logo.svg?width=160'),
  ('IVZ', 'IVZ.US', 'USD', 'stock', 'Invesco', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'IN', null),
  ('INVH', 'INVH.US', 'USD', 'stock', 'Invitation Homes', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'IN', null),
  ('IQV', 'IQV.US', 'USD', 'stock', 'IQVIA', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'IQ', 'https://commons.wikimedia.org/wiki/Special:FilePath/Iqvia-logo-color.svg?width=160'),
  ('IRM', 'IRM.US', 'USD', 'stock', 'Iron Mountain', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'IR', null),
  ('JBHT', 'JBHT.US', 'USD', 'stock', 'J.B. Hunt', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'JB', null),
  ('JBL', 'JBL.US', 'USD', 'stock', 'Jabil', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'JA', 'https://eodhd.com/img/logos/US/jbl.png'),
  ('JKHY', 'JKHY.US', 'USD', 'stock', 'Jack Henry & Associates', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'JA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Jack-henry-logo.svg?width=160'),
  ('J', 'J.US', 'USD', 'stock', 'Jacobs Solutions', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'JA', null),
  ('JNJ', 'JNJ.US', 'USD', 'stock', 'Johnson & Johnson', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'JO', 'https://commons.wikimedia.org/wiki/Special:FilePath/JNJ_Logo_New.svg?width=160'),
  ('JCI', 'JCI.US', 'USD', 'stock', 'Johnson Controls', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'JO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Johnson_Controls_old_logo.svg?width=160'),
  ('KVUE', 'KVUE.US', 'USD', 'stock', 'Kenvue', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'KE', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kenvue_logo.svg?width=160'),
  ('KDP', 'KDP.US', 'USD', 'stock', 'Keurig Dr Pepper', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'KE', 'https://commons.wikimedia.org/wiki/Special:FilePath/Keurig_Dr_Pepper.svg?width=160'),
  ('KEY', 'KEY.US', 'USD', 'stock', 'KeyCorp', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'KE', 'https://eodhd.com/img/logos/US/key.png'),
  ('KEYS', 'KEYS.US', 'USD', 'stock', 'Keysight Technologies', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'KE', null),
  ('KMB', 'KMB.US', 'USD', 'stock', 'Kimberly-Clark', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'KI', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kimberly-Clark_logo.svg?width=160'),
  ('KIM', 'KIM.US', 'USD', 'stock', 'Kimco Realty', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'KI', 'https://eodhd.com/img/logos/US/kim.png'),
  ('KMI', 'KMI.US', 'USD', 'stock', 'Kinder Morgan', 'US', 'États-Unis', 'Énergie-pétrole', 'Energy and oil', 'energy', 'us', 'KI', null),
  ('KKR', 'KKR.US', 'USD', 'stock', 'KKR & Co.', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'KK', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kohlberg_Kravis_Roberts_%28logo%29.svg?width=160'),
  ('KLAC', 'KLAC.US', 'USD', 'stock', 'KLA Corporation', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'KL', 'https://commons.wikimedia.org/wiki/Special:FilePath/KLA_Corp._logo.svg?width=160'),
  ('KHC', 'KHC.US', 'USD', 'stock', 'Kraft Heinz', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'KR', 'https://eodhd.com/img/logos/US/khc.png'),
  ('KR', 'KR.US', 'USD', 'stock', 'Kroger', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'KR', null),
  ('LHX', 'LHX.US', 'USD', 'stock', 'L3Harris', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'L3', 'https://commons.wikimedia.org/wiki/Special:FilePath/L3Harris_Technologies_logo.svg?width=160'),
  ('LH', 'LH.US', 'USD', 'stock', 'Labcorp', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'LA', null),
  ('LRCX', 'LRCX.US', 'USD', 'stock', 'Lam Research', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'LA', 'https://eodhd.com/img/logos/US/lrcx.png'),
  ('LVS', 'LVS.US', 'USD', 'stock', 'Las Vegas Sands', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'LA', null),
  ('LDOS', 'LDOS.US', 'USD', 'stock', 'Leidos', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'LE', 'https://eodhd.com/img/logos/US/ldos.png'),
  ('LEN', 'LEN.US', 'USD', 'stock', 'Lennar', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'LE', 'https://commons.wikimedia.org/wiki/Special:FilePath/Lennar_Corporation_logo.png?width=160'),
  ('LII', 'LII.US', 'USD', 'stock', 'Lennox International', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'LE', null),
  ('LLY', 'LLY.US', 'USD', 'stock', 'Lilly (Eli)', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'LI', 'https://commons.wikimedia.org/wiki/Special:FilePath/Eli_Lilly_and_Company.svg?width=160'),
  ('LIN', 'LIN.US', 'USD', 'stock', 'Linde plc', 'US', 'États-Unis', 'Matériaux', 'Materials', 'materials', 'us', 'LI', 'https://commons.wikimedia.org/wiki/Special:FilePath/TheLindeGroup-Logo.svg?width=160'),
  ('LYV', 'LYV.US', 'USD', 'stock', 'Live Nation Entertainment', 'US', 'États-Unis', 'Communication-médias', 'Communication services', 'telecom', 'us', 'LI', null),
  ('LMT', 'LMT.US', 'USD', 'stock', 'Lockheed Martin', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'LO', 'https://eodhd.com/img/logos/US/lmt.png'),
  ('L', 'L.US', 'USD', 'stock', 'Loews Corporation', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'LO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Loews-Corporation-Logo.svg?width=160'),
  ('LOW', 'LOW.US', 'USD', 'stock', 'Lowe''s', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'LO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Lowes_Companies_Logo.svg?width=160'),
  ('LULU', 'LULU.US', 'USD', 'stock', 'Lululemon Athletica', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'LU', 'https://eodhd.com/img/logos/US/lulu.png'),
  ('LITE', 'LITE.US', 'USD', 'stock', 'Lumentum', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'LU', null),
  ('LYB', 'LYB.US', 'USD', 'stock', 'LyondellBasell', 'US', 'États-Unis', 'Matériaux', 'Materials', 'materials', 'us', 'LY', 'https://eodhd.com/img/logos/US/lyb.png'),
  ('MTB', 'MTB.US', 'USD', 'stock', 'M&T Bank', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'MT', 'https://eodhd.com/img/logos/US/mtb.png'),
  ('MPC', 'MPC.US', 'USD', 'stock', 'Marathon Petroleum', 'US', 'États-Unis', 'Énergie-pétrole', 'Energy and oil', 'energy', 'us', 'MA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Marathon_Oil_Logo.svg?width=160'),
  ('MAR', 'MAR.US', 'USD', 'stock', 'Marriott International', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'MA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Marriott_International.svg?width=160'),
  ('MRSH', 'MRSH.US', 'USD', 'stock', 'Marsh McLennan', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'MA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Marsh_%26_McLennan_Companies.svg?width=160'),
  ('MLM', 'MLM.US', 'USD', 'stock', 'Martin Marietta Materials', 'US', 'États-Unis', 'Matériaux', 'Materials', 'materials', 'us', 'MA', null),
  ('MRVL', 'MRVL.US', 'USD', 'stock', 'Marvell Technology', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'MA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Marvell_Logo.svg?width=160'),
  ('MAS', 'MAS.US', 'USD', 'stock', 'Masco', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'MA', 'https://eodhd.com/img/logos/US/mas.png'),
  ('MKC', 'MKC.US', 'USD', 'stock', 'McCormick & Company', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'MC', 'https://eodhd.com/img/logos/US/mkc.png'),
  ('MCD', 'MCD.US', 'USD', 'stock', 'McDonald''s', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'MC', null),
  ('MCK', 'MCK.US', 'USD', 'stock', 'McKesson Corporation', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'MC', 'https://eodhd.com/img/logos/US/mck.png'),
  ('MDT', 'MDT.US', 'USD', 'stock', 'Medtronic', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'ME', 'https://commons.wikimedia.org/wiki/Special:FilePath/Medtronic_logo.svg?width=160'),
  ('MRK', 'MRK.US', 'USD', 'stock', 'Merck & Co.', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'ME', 'https://eodhd.com/img/logos/US/mrk.png'),
  ('META', 'META.US', 'USD', 'stock', 'Meta Platforms', 'US', 'États-Unis', 'Communication-médias', 'Communication services', 'telecom', 'us', 'ME', 'https://eodhd.com/img/logos/US/meta.png'),
  ('MET', 'MET.US', 'USD', 'stock', 'MetLife', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'ME', 'https://commons.wikimedia.org/wiki/Special:FilePath/MetLife_logo.svg?width=160'),
  ('MTD', 'MTD.US', 'USD', 'stock', 'Mettler Toledo', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'ME', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mettler_Toledo.svg?width=160'),
  ('MGM', 'MGM.US', 'USD', 'stock', 'MGM Resorts', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'MG', 'https://eodhd.com/img/logos/US/mgm.png'),
  ('MCHP', 'MCHP.US', 'USD', 'stock', 'Microchip Technology', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'MI', 'https://commons.wikimedia.org/wiki/Special:FilePath/Microchip-Logo.svg?width=160'),
  ('MU', 'MU.US', 'USD', 'stock', 'Micron Technology', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'MI', 'https://eodhd.com/img/logos/US/mu.png'),
  ('MAA', 'MAA.US', 'USD', 'stock', 'Mid-America Apartment Communities', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'MI', null),
  ('MRNA', 'MRNA.US', 'USD', 'stock', 'Moderna', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'MO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Moderna_logo.svg?width=160'),
  ('MDLZ', 'MDLZ.US', 'USD', 'stock', 'Mondelez International', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'MO', 'https://eodhd.com/img/logos/US/mdlz.png'),
  ('MPWR', 'MPWR.US', 'USD', 'stock', 'Monolithic Power Systems', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'MO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Monolithic_Power_Systems_Logo.svg?width=160'),
  ('MNST', 'MNST.US', 'USD', 'stock', 'Monster Beverage', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'MO', 'https://eodhd.com/img/logos/US/mnst.png'),
  ('MCO', 'MCO.US', 'USD', 'stock', 'Moody''s Corporation', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'MO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Moody%27s_new_logo.png?width=160'),
  ('MS', 'MS.US', 'USD', 'stock', 'Morgan Stanley', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'MO', 'https://eodhd.com/img/logos/US/ms.png'),
  ('MOS', 'MOS.US', 'USD', 'stock', 'Mosaic Company (The)', 'US', 'États-Unis', 'Matériaux', 'Materials', 'materials', 'us', 'MO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mosaic_Logo.svg?width=160'),
  ('MSI', 'MSI.US', 'USD', 'stock', 'Motorola Solutions', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'MO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Motorola_Solutions_Logo.svg?width=160'),
  ('MSCI', 'MSCI.US', 'USD', 'stock', 'MSCI', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'MS', 'https://commons.wikimedia.org/wiki/Special:FilePath/MSCI_logo.svg?width=160'),
  ('NDAQ', 'NDAQ.US', 'USD', 'stock', 'Nasdaq, Inc.', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'NA', 'https://eodhd.com/img/logos/US/ndaq.png'),
  ('NTAP', 'NTAP.US', 'USD', 'stock', 'NetApp', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'NE', 'https://commons.wikimedia.org/wiki/Special:FilePath/NetApp_logo.svg?width=160'),
  ('NFLX', 'NFLX.US', 'USD', 'stock', 'Netflix', 'US', 'États-Unis', 'Communication-médias', 'Communication services', 'telecom', 'us', 'NE', 'https://eodhd.com/img/logos/US/nflx.png'),
  ('NEM', 'NEM.US', 'USD', 'stock', 'Newmont', 'US', 'États-Unis', 'Matériaux', 'Materials', 'materials', 'us', 'NE', 'https://commons.wikimedia.org/wiki/Special:FilePath/Newmont-Mining-Logo.svg?width=160'),
  ('NWSA', 'NWSA.US', 'USD', 'stock', 'News Corp', 'US', 'États-Unis', 'Communication-médias', 'Communication services', 'telecom', 'us', 'NE', null),
  ('NWS', 'NWS.US', 'USD', 'stock', 'News Corp', 'US', 'États-Unis', 'Communication-médias', 'Communication services', 'telecom', 'us', 'NE', null),
  ('NEE', 'NEE.US', 'USD', 'stock', 'NextEra Energy', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'NE', 'https://eodhd.com/img/logos/US/nee.png'),
  ('NKE', 'NKE.US', 'USD', 'stock', 'Nike, Inc.', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'NI', 'https://eodhd.com/img/logos/US/nke.png'),
  ('NI', 'NI.US', 'USD', 'stock', 'NiSource', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'NI', 'https://eodhd.com/img/logos/US/ni.png'),
  ('NDSN', 'NDSN.US', 'USD', 'stock', 'Nordson Corporation', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'NO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Nordson_Corporation_Logo.svg?width=160'),
  ('NSC', 'NSC.US', 'USD', 'stock', 'Norfolk Southern', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'NO', null),
  ('NTRS', 'NTRS.US', 'USD', 'stock', 'Northern Trust', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'NO', 'https://eodhd.com/img/logos/US/ntrs.png'),
  ('NOC', 'NOC.US', 'USD', 'stock', 'Northrop Grumman', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'NO', null),
  ('NCLH', 'NCLH.US', 'USD', 'stock', 'Norwegian Cruise Line Holdings', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'NO', 'https://commons.wikimedia.org/wiki/Special:FilePath/NCLH_logo.png?width=160'),
  ('NRG', 'NRG.US', 'USD', 'stock', 'NRG Energy', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'NR', 'https://commons.wikimedia.org/wiki/Special:FilePath/Logo_NRG_Energy.svg?width=160'),
  ('NUE', 'NUE.US', 'USD', 'stock', 'Nucor', 'US', 'États-Unis', 'Matériaux', 'Materials', 'materials', 'us', 'NU', 'https://commons.wikimedia.org/wiki/Special:FilePath/Nucor.svg?width=160'),
  ('NVR', 'NVR.US', 'USD', 'stock', 'NVR, Inc.', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'NV', 'https://eodhd.com/img/logos/US/nvr.png'),
  ('NXPI', 'NXPI.US', 'USD', 'stock', 'NXP Semiconductors', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'NX', 'https://commons.wikimedia.org/wiki/Special:FilePath/NXP_Semiconductors_logo_2023.svg?width=160'),
  ('ORLY', 'ORLY.US', 'USD', 'stock', 'O''Reilly Automotive', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'auto', 'us', 'OR', 'https://commons.wikimedia.org/wiki/Special:FilePath/O%27Reilly_Auto_Parts_Logo.svg?width=160'),
  ('OXY', 'OXY.US', 'USD', 'stock', 'Occidental Petroleum', 'US', 'États-Unis', 'Énergie-pétrole', 'Energy and oil', 'energy', 'us', 'OC', 'https://commons.wikimedia.org/wiki/Special:FilePath/Occidental-Petroleum-Logo.svg?width=160'),
  ('ODFL', 'ODFL.US', 'USD', 'stock', 'Old Dominion', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'OL', null),
  ('OMC', 'OMC.US', 'USD', 'stock', 'Omnicom Group', 'US', 'États-Unis', 'Communication-médias', 'Communication services', 'telecom', 'us', 'OM', 'https://commons.wikimedia.org/wiki/Special:FilePath/Omnicom.svg?width=160'),
  ('ON', 'ON.US', 'USD', 'stock', 'ON Semiconductor', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'ON', null),
  ('OKE', 'OKE.US', 'USD', 'stock', 'Oneok', 'US', 'États-Unis', 'Énergie-pétrole', 'Energy and oil', 'energy', 'us', 'ON', null),
  ('ORCL', 'ORCL.US', 'USD', 'stock', 'Oracle Corporation', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'OR', 'https://eodhd.com/img/logos/US/orcl.png'),
  ('OTIS', 'OTIS.US', 'USD', 'stock', 'Otis Worldwide', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'OT', 'https://commons.wikimedia.org/wiki/Special:FilePath/Otis_logo.SVG?width=160'),
  ('PCAR', 'PCAR.US', 'USD', 'stock', 'Paccar', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'PA', 'https://commons.wikimedia.org/wiki/Special:FilePath/PACCAR-logo.svg?width=160'),
  ('PKG', 'PKG.US', 'USD', 'stock', 'Packaging Corporation of America', 'US', 'États-Unis', 'Matériaux', 'Materials', 'materials', 'us', 'PA', 'https://eodhd.com/img/logos/US/pkg.png'),
  ('PLTR', 'PLTR.US', 'USD', 'stock', 'Palantir Technologies', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'PA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Palantir_Technologies_logo.svg?width=160'),
  ('PANW', 'PANW.US', 'USD', 'stock', 'Palo Alto Networks', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'PA', 'https://eodhd.com/img/logos/US/panw.png'),
  ('PSKY', 'PSKY.US', 'USD', 'stock', 'Paramount Skydance Corporation', 'US', 'États-Unis', 'Communication-médias', 'Communication services', 'telecom', 'us', 'PA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Paramount_Skydance_Logo.svg?width=160'),
  ('PH', 'PH.US', 'USD', 'stock', 'Parker Hannifin', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'PA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Parker_Hannifin.svg?width=160'),
  ('PAYX', 'PAYX.US', 'USD', 'stock', 'Paychex', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'PA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Paychex_logo.svg?width=160'),
  ('PYPL', 'PYPL.US', 'USD', 'stock', 'PayPal', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'PA', 'https://eodhd.com/img/logos/US/pypl.png'),
  ('PNR', 'PNR.US', 'USD', 'stock', 'Pentair', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'PE', 'https://commons.wikimedia.org/wiki/Special:FilePath/Pentair_Schroff_Logo.svg?width=160'),
  ('PEP', 'PEP.US', 'USD', 'stock', 'PepsiCo', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'PE', 'https://eodhd.com/img/logos/US/pep.png'),
  ('PFE', 'PFE.US', 'USD', 'stock', 'Pfizer', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'PF', 'https://eodhd.com/img/logos/US/pfe.png'),
  ('PCG', 'PCG.US', 'USD', 'stock', 'PG&E Corporation', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'PG', 'https://eodhd.com/img/logos/US/pcg.png'),
  ('PM', 'PM.US', 'USD', 'stock', 'Philip Morris International', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'PH', 'https://commons.wikimedia.org/wiki/Special:FilePath/Pmi_logo_text_only.svg?width=160'),
  ('PSX', 'PSX.US', 'USD', 'stock', 'Phillips 66', 'US', 'États-Unis', 'Énergie-pétrole', 'Energy and oil', 'energy', 'us', 'PH', 'https://commons.wikimedia.org/wiki/Special:FilePath/Phillips_66_logo.svg?width=160'),
  ('PNW', 'PNW.US', 'USD', 'stock', 'Pinnacle West Capital', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'PI', 'https://commons.wikimedia.org/wiki/Special:FilePath/Pinnacle_West_Capital_logo.png?width=160'),
  ('PNC', 'PNC.US', 'USD', 'stock', 'PNC Financial Services', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'PN', 'https://eodhd.com/img/logos/US/pnc.png'),
  ('PPG', 'PPG.US', 'USD', 'stock', 'PPG Industries', 'US', 'États-Unis', 'Matériaux', 'Materials', 'materials', 'us', 'PP', 'https://commons.wikimedia.org/wiki/Special:FilePath/PPG_Logo.svg?width=160'),
  ('PPL', 'PPL.US', 'USD', 'stock', 'PPL Corporation', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'PP', 'https://eodhd.com/img/logos/US/ppl.png'),
  ('PFG', 'PFG.US', 'USD', 'stock', 'Principal Financial Group', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'PR', 'https://commons.wikimedia.org/wiki/Special:FilePath/Principal_Financial_Group_logo.svg?width=160'),
  ('PG', 'PG.US', 'USD', 'stock', 'Procter & Gamble', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'PR', 'https://commons.wikimedia.org/wiki/Special:FilePath/Procter_%26_Gamble_logo.svg?width=160'),
  ('PGR', 'PGR.US', 'USD', 'stock', 'Progressive Corporation', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'PR', 'https://eodhd.com/img/logos/US/pgr.png'),
  ('PLD', 'PLD.US', 'USD', 'stock', 'Prologis', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'PR', 'https://eodhd.com/img/logos/US/pld.png'),
  ('PRU', 'PRU.US', 'USD', 'stock', 'Prudential Financial', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'PR', null),
  ('PEG', 'PEG.US', 'USD', 'stock', 'Public Service Enterprise Group', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'PU', 'https://eodhd.com/img/logos/US/peg.png'),
  ('PTC', 'PTC.US', 'USD', 'stock', 'PTC Inc.', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'PT', 'https://eodhd.com/img/logos/US/ptc.png'),
  ('PSA', 'PSA.US', 'USD', 'stock', 'Public Storage', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'PU', 'https://commons.wikimedia.org/wiki/Special:FilePath/Public_Storage_logo.svg?width=160'),
  ('PHM', 'PHM.US', 'USD', 'stock', 'PulteGroup', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'PU', 'https://eodhd.com/img/logos/US/phm.png'),
  ('PWR', 'PWR.US', 'USD', 'stock', 'Quanta Services', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'QU', null),
  ('QCOM', 'QCOM.US', 'USD', 'stock', 'Qualcomm', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'QU', 'https://commons.wikimedia.org/wiki/Special:FilePath/Qualcomm-Logo.svg?width=160'),
  ('DGX', 'DGX.US', 'USD', 'stock', 'Quest Diagnostics', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'QU', null),
  ('Q', 'Q.US', 'USD', 'stock', 'Qnity Electronics', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'QN', 'https://eodhd.com/img/logos/US/q.png'),
  ('RL', 'RL.US', 'USD', 'stock', 'Ralph Lauren Corporation', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'RA', 'https://eodhd.com/img/logos/US/rl.png'),
  ('RJF', 'RJF.US', 'USD', 'stock', 'Raymond James Financial', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'RA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Raymond_James_Logo.JPG?width=160'),
  ('RTX', 'RTX.US', 'USD', 'stock', 'RTX Corporation', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'RT', 'https://commons.wikimedia.org/wiki/Special:FilePath/Raytheon_Technologies_logo.svg?width=160'),
  ('O', 'O.US', 'USD', 'stock', 'Realty Income', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'RE', 'https://eodhd.com/img/logos/US/o.png'),
  ('REG', 'REG.US', 'USD', 'stock', 'Regency Centers', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'RE', 'https://commons.wikimedia.org/wiki/Special:FilePath/Regency_Centers_Corporation_logo.svg?width=160'),
  ('REGN', 'REGN.US', 'USD', 'stock', 'Regeneron Pharmaceuticals', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'RE', 'https://eodhd.com/img/logos/US/regn.png'),
  ('RF', 'RF.US', 'USD', 'stock', 'Regions Financial Corporation', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'RE', 'https://eodhd.com/img/logos/US/rf.png'),
  ('RSG', 'RSG.US', 'USD', 'stock', 'Republic Services', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'RE', 'https://commons.wikimedia.org/wiki/Special:FilePath/Republic_Services_logo.svg?width=160'),
  ('RMD', 'RMD.US', 'USD', 'stock', 'ResMed', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'RE', 'https://commons.wikimedia.org/wiki/Special:FilePath/Resmed_Logo_2025.png?width=160'),
  ('RVTY', 'RVTY.US', 'USD', 'stock', 'Revvity', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'RE', 'https://commons.wikimedia.org/wiki/Special:FilePath/Revvity_Logo.png?width=160'),
  ('HOOD', 'HOOD.US', 'USD', 'stock', 'Robinhood Markets', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'RO', 'https://eodhd.com/img/logos/US/hood.png'),
  ('ROK', 'ROK.US', 'USD', 'stock', 'Rockwell Automation', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'RO', null),
  ('ROL', 'ROL.US', 'USD', 'stock', 'Rollins, Inc.', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'RO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Rollins%2C_Inc._Logo.svg?width=160'),
  ('ROP', 'ROP.US', 'USD', 'stock', 'Roper Technologies', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'RO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Roper_Technologies_logo.svg?width=160'),
  ('ROST', 'ROST.US', 'USD', 'stock', 'Ross Stores', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'RO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ross_Stores_logo.svg?width=160'),
  ('RCL', 'RCL.US', 'USD', 'stock', 'Royal Caribbean Group', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'RO', 'https://eodhd.com/img/logos/US/rcl.png'),
  ('SPGI', 'SPGI.US', 'USD', 'stock', 'S&P Global', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'SP', 'https://commons.wikimedia.org/wiki/Special:FilePath/S%26P_Global_logo.svg?width=160'),
  ('CRM', 'CRM.US', 'USD', 'stock', 'Salesforce', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'SA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Salesforce.com_logo.svg?width=160'),
  ('SNDK', 'SNDK.US', 'USD', 'stock', 'Sandisk', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'SA', null),
  ('SBAC', 'SBAC.US', 'USD', 'stock', 'SBA Communications', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'SB', 'https://commons.wikimedia.org/wiki/Special:FilePath/SBA_Communications_Logo.svg?width=160'),
  ('SLB', 'SLB.US', 'USD', 'stock', 'Schlumberger', 'US', 'États-Unis', 'Énergie-pétrole', 'Energy and oil', 'energy', 'us', 'SC', null),
  ('STX', 'STX.US', 'USD', 'stock', 'Seagate Technology', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'SE', 'https://commons.wikimedia.org/wiki/Special:FilePath/Seagate_logo.svg?width=160'),
  ('SRE', 'SRE.US', 'USD', 'stock', 'Sempra', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'SE', 'https://eodhd.com/img/logos/US/sre.png'),
  ('NOW', 'NOW.US', 'USD', 'stock', 'ServiceNow', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'SE', 'https://eodhd.com/img/logos/US/now.png'),
  ('SHW', 'SHW.US', 'USD', 'stock', 'Sherwin-Williams', 'US', 'États-Unis', 'Matériaux', 'Materials', 'materials', 'us', 'SH', 'https://commons.wikimedia.org/wiki/Special:FilePath/Sherwin-Williams_wordmark.svg?width=160'),
  ('SPG', 'SPG.US', 'USD', 'stock', 'Simon Property Group', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'SI', 'https://eodhd.com/img/logos/US/spg.png'),
  ('SWKS', 'SWKS.US', 'USD', 'stock', 'Skyworks Solutions', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'SK', 'https://eodhd.com/img/logos/US/swks.png'),
  ('SJM', 'SJM.US', 'USD', 'stock', 'J.M. Smucker Company (The)', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'JM', 'https://commons.wikimedia.org/wiki/Special:FilePath/Smuckers_logo.svg?width=160'),
  ('SW', 'SW.US', 'USD', 'stock', 'Smurfit Westrock', 'US', 'États-Unis', 'Matériaux', 'Materials', 'materials', 'us', 'SM', 'https://commons.wikimedia.org/wiki/Special:FilePath/Smurfit_Kappa_Group_Logo.svg?width=160'),
  ('SNA', 'SNA.US', 'USD', 'stock', 'Snap-on', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'SN', 'https://commons.wikimedia.org/wiki/Special:FilePath/Snap-on_logo.svg?width=160'),
  ('SOLV', 'SOLV.US', 'USD', 'stock', 'Solventum', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'SO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Solventum_logo_2024.png?width=160'),
  ('SO', 'SO.US', 'USD', 'stock', 'Southern Company', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'SO', 'https://commons.wikimedia.org/wiki/Special:FilePath/Southern_Company_logo.svg?width=160'),
  ('LUV', 'LUV.US', 'USD', 'stock', 'Southwest Airlines', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'SO', 'https://eodhd.com/img/logos/US/luv.png'),
  ('SWK', 'SWK.US', 'USD', 'stock', 'Stanley Black & Decker', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'ST', 'https://eodhd.com/img/logos/US/swk.png'),
  ('SBUX', 'SBUX.US', 'USD', 'stock', 'Starbucks', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'ST', 'https://commons.wikimedia.org/wiki/Special:FilePath/Starbucks_coffee_wordmark.png?width=160'),
  ('STT', 'STT.US', 'USD', 'stock', 'State Street Corporation', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'ST', 'https://commons.wikimedia.org/wiki/Special:FilePath/State-street-logo-final.svg?width=160'),
  ('STLD', 'STLD.US', 'USD', 'stock', 'Steel Dynamics', 'US', 'États-Unis', 'Matériaux', 'Materials', 'materials', 'us', 'ST', 'https://eodhd.com/img/logos/US/stld.png'),
  ('STE', 'STE.US', 'USD', 'stock', 'Steris', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'ST', 'https://eodhd.com/img/logos/US/ste.png'),
  ('SYK', 'SYK.US', 'USD', 'stock', 'Stryker Corporation', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'ST', 'https://eodhd.com/img/logos/US/syk.png'),
  ('SMCI', 'SMCI.US', 'USD', 'stock', 'Supermicro', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'SU', 'https://commons.wikimedia.org/wiki/Special:FilePath/Super_Micro_Computer_Logo.svg?width=160'),
  ('SYF', 'SYF.US', 'USD', 'stock', 'Synchrony Financial', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'SY', 'https://commons.wikimedia.org/wiki/Special:FilePath/Synchrony_Financial_logo.svg?width=160'),
  ('SNPS', 'SNPS.US', 'USD', 'stock', 'Synopsys', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'SY', 'https://commons.wikimedia.org/wiki/Special:FilePath/Synopsys_Logo.svg?width=160'),
  ('SYY', 'SYY.US', 'USD', 'stock', 'Sysco', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'SY', 'https://commons.wikimedia.org/wiki/Special:FilePath/Sysco-Logo.svg?width=160'),
  ('TMUS', 'TMUS.US', 'USD', 'stock', 'T-Mobile US', 'US', 'États-Unis', 'Communication-médias', 'Communication services', 'telecom', 'us', 'TM', null),
  ('TROW', 'TROW.US', 'USD', 'stock', 'T. Rowe Price', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'TR', null),
  ('TTWO', 'TTWO.US', 'USD', 'stock', 'Take-Two Interactive', 'US', 'États-Unis', 'Communication-médias', 'Communication services', 'telecom', 'us', 'TA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Take-Two_Interactive_Logo.svg?width=160'),
  ('TPR', 'TPR.US', 'USD', 'stock', 'Tapestry, Inc.', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'TA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Tapestry_logo.svg?width=160'),
  ('TRGP', 'TRGP.US', 'USD', 'stock', 'Targa Resources', 'US', 'États-Unis', 'Énergie-pétrole', 'Energy and oil', 'energy', 'us', 'TA', null),
  ('TGT', 'TGT.US', 'USD', 'stock', 'Target Corporation', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'TA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Target_logo.svg?width=160'),
  ('TEL', 'TEL.US', 'USD', 'stock', 'TE Connectivity', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'TE', 'https://commons.wikimedia.org/wiki/Special:FilePath/TE_Connectivity_logo.svg?width=160'),
  ('TDY', 'TDY.US', 'USD', 'stock', 'Teledyne Technologies', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'TE', 'https://commons.wikimedia.org/wiki/Special:FilePath/Teledyne_logo.svg?width=160'),
  ('TER', 'TER.US', 'USD', 'stock', 'Teradyne', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'TE', null),
  ('TXN', 'TXN.US', 'USD', 'stock', 'Texas Instruments', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'TE', 'https://commons.wikimedia.org/wiki/Special:FilePath/TexasInstruments-Logo.svg?width=160'),
  ('TPL', 'TPL.US', 'USD', 'stock', 'Texas Pacific Land Corporation', 'US', 'États-Unis', 'Énergie-pétrole', 'Energy and oil', 'energy', 'us', 'TE', null),
  ('TXT', 'TXT.US', 'USD', 'stock', 'Textron', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'TE', 'https://eodhd.com/img/logos/US/txt.png'),
  ('TMO', 'TMO.US', 'USD', 'stock', 'Thermo Fisher Scientific', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'TH', 'https://eodhd.com/img/logos/US/tmo.png'),
  ('TJX', 'TJX.US', 'USD', 'stock', 'TJX Companies', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'TJ', 'https://eodhd.com/img/logos/US/tjx.png'),
  ('TKO', 'TKO.US', 'USD', 'stock', 'TKO Group Holdings', 'US', 'États-Unis', 'Communication-médias', 'Communication services', 'telecom', 'us', 'TK', 'https://commons.wikimedia.org/wiki/Special:FilePath/TKO_Group_Holdings_Logo_2024.svg?width=160'),
  ('TSCO', 'TSCO.US', 'USD', 'stock', 'Tractor Supply', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'TR', 'https://commons.wikimedia.org/wiki/Special:FilePath/TractorSupplyCompanylogo.svg?width=160'),
  ('TT', 'TT.US', 'USD', 'stock', 'Trane Technologies', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'TR', null),
  ('TDG', 'TDG.US', 'USD', 'stock', 'TransDigm Group', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'TR', 'https://eodhd.com/img/logos/US/tdg.png'),
  ('TRV', 'TRV.US', 'USD', 'stock', 'Travelers Companies (The)', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'TR', null),
  ('TRMB', 'TRMB.US', 'USD', 'stock', 'Trimble Inc.', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'TR', 'https://commons.wikimedia.org/wiki/Special:FilePath/Trimble_Logo.svg?width=160'),
  ('TFC', 'TFC.US', 'USD', 'stock', 'Truist Financial', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'TR', 'https://commons.wikimedia.org/wiki/Special:FilePath/Truist_Financial_logo.svg?width=160'),
  ('TYL', 'TYL.US', 'USD', 'stock', 'Tyler Technologies', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'TY', 'https://eodhd.com/img/logos/US/tyl.png'),
  ('TSN', 'TSN.US', 'USD', 'stock', 'Tyson Foods', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'TY', 'https://commons.wikimedia.org/wiki/Special:FilePath/Tyson_Foods_logo.svg?width=160'),
  ('USB', 'USB.US', 'USD', 'stock', 'U.S. Bancorp', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'US', 'https://eodhd.com/img/logos/US/usb.png'),
  ('UBER', 'UBER.US', 'USD', 'stock', 'Uber', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'UB', null),
  ('UDR', 'UDR.US', 'USD', 'stock', 'UDR, Inc.', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'UD', 'https://commons.wikimedia.org/wiki/Special:FilePath/UDR%2C_Inc._logo.png?width=160'),
  ('ULTA', 'ULTA.US', 'USD', 'stock', 'Ulta Beauty', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'UL', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ulta_Beauty_logo.svg?width=160'),
  ('UNP', 'UNP.US', 'USD', 'stock', 'Union Pacific Corporation', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'UN', 'https://commons.wikimedia.org/wiki/Special:FilePath/Union_pacific_railroad_logo.svg?width=160'),
  ('UAL', 'UAL.US', 'USD', 'stock', 'United Airlines Holdings', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'UN', 'https://eodhd.com/img/logos/US/ual.png'),
  ('UPS', 'UPS.US', 'USD', 'stock', 'United Parcel Service', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'UN', null),
  ('URI', 'URI.US', 'USD', 'stock', 'United Rentals', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'UN', 'https://commons.wikimedia.org/wiki/Special:FilePath/United_Rentals_Logo.svg?width=160'),
  ('UNH', 'UNH.US', 'USD', 'stock', 'UnitedHealth Group', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'UN', 'https://eodhd.com/img/logos/US/unh.png'),
  ('UHS', 'UHS.US', 'USD', 'stock', 'Universal Health Services', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'UN', 'https://eodhd.com/img/logos/US/uhs.png'),
  ('VLO', 'VLO.US', 'USD', 'stock', 'Valero Energy', 'US', 'États-Unis', 'Énergie-pétrole', 'Energy and oil', 'energy', 'us', 'VA', 'https://eodhd.com/img/logos/US/vlo.png'),
  ('VEEV', 'VEEV.US', 'USD', 'stock', 'Veeva Systems', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'VE', 'https://commons.wikimedia.org/wiki/Special:FilePath/Veeva_Systems_Logo.svg?width=160'),
  ('VTR', 'VTR.US', 'USD', 'stock', 'Ventas', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'VE', 'https://eodhd.com/img/logos/US/vtr.png'),
  ('VLTO', 'VLTO.US', 'USD', 'stock', 'Veralto', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'VE', null),
  ('VRSN', 'VRSN.US', 'USD', 'stock', 'Verisign', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'VE', 'https://commons.wikimedia.org/wiki/Special:FilePath/Verisign_logo.svg?width=160'),
  ('VRSK', 'VRSK.US', 'USD', 'stock', 'Verisk Analytics', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'VE', null),
  ('VZ', 'VZ.US', 'USD', 'stock', 'Verizon', 'US', 'États-Unis', 'Communication-médias', 'Communication services', 'telecom', 'us', 'VE', 'https://eodhd.com/img/logos/US/vz.png'),
  ('VRTX', 'VRTX.US', 'USD', 'stock', 'Vertex Pharmaceuticals', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'VE', 'https://commons.wikimedia.org/wiki/Special:FilePath/VertexPharma-logo2.png?width=160'),
  ('VRT', 'VRT.US', 'USD', 'stock', 'Vertiv', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'VE', 'https://commons.wikimedia.org/wiki/Special:FilePath/Vertiv_logo.svg?width=160'),
  ('VTRS', 'VTRS.US', 'USD', 'stock', 'Viatris', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'VI', 'https://commons.wikimedia.org/wiki/Special:FilePath/Viatris.svg?width=160'),
  ('VICI', 'VICI.US', 'USD', 'stock', 'Vici Properties', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'VI', 'https://commons.wikimedia.org/wiki/Special:FilePath/Vici_Properties_logo.svg?width=160'),
  ('VST', 'VST.US', 'USD', 'stock', 'Vistra Corp', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'VI', null),
  ('VMRK', 'VMRK.US', 'USD', 'stock', 'Vivmark Residential', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'VI', 'https://commons.wikimedia.org/wiki/Special:FilePath/Equity_Residential_logo.svg?width=160'),
  ('VMC', 'VMC.US', 'USD', 'stock', 'Vulcan Materials Company', 'US', 'États-Unis', 'Matériaux', 'Materials', 'materials', 'us', 'VU', 'https://commons.wikimedia.org/wiki/Special:FilePath/Vulcan_Materials_logo.svg?width=160'),
  ('WRB', 'WRB.US', 'USD', 'stock', 'W. R. Berkley Corporation', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'WR', 'https://eodhd.com/img/logos/US/wrb.png'),
  ('GWW', 'GWW.US', 'USD', 'stock', 'W. W. Grainger', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'WW', 'https://commons.wikimedia.org/wiki/Special:FilePath/W._W._Grainger_logo.svg?width=160'),
  ('WAB', 'WAB.US', 'USD', 'stock', 'Wabtec', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'WA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Wabtec_logo.svg?width=160'),
  ('WMT', 'WMT.US', 'USD', 'stock', 'Walmart', 'US', 'États-Unis', 'Consommation courante', 'Consumer staples', 'consumer', 'us', 'WA', 'https://eodhd.com/img/logos/US/wmt.png'),
  ('DIS', 'DIS.US', 'USD', 'stock', 'Walt Disney Company (The)', 'US', 'États-Unis', 'Communication-médias', 'Communication services', 'telecom', 'us', 'WA', 'https://eodhd.com/img/logos/US/dis.png'),
  ('WBD', 'WBD.US', 'USD', 'stock', 'Warner Bros. Discovery', 'US', 'États-Unis', 'Communication-médias', 'Communication services', 'telecom', 'us', 'WA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Warner_Bros._Discovery.svg?width=160'),
  ('WM', 'WM.US', 'USD', 'stock', 'Waste Management', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'WA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Waste-management.svg?width=160'),
  ('WAT', 'WAT.US', 'USD', 'stock', 'Waters Corporation', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'WA', null),
  ('WEC', 'WEC.US', 'USD', 'stock', 'WEC Energy Group', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'WE', 'https://eodhd.com/img/logos/US/wec.png'),
  ('WELL', 'WELL.US', 'USD', 'stock', 'Welltower', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'WE', 'https://commons.wikimedia.org/wiki/Special:FilePath/Welltower_Logo_2025.svg?width=160'),
  ('WST', 'WST.US', 'USD', 'stock', 'West Pharmaceutical Services', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'WE', 'https://eodhd.com/img/logos/US/wst.png'),
  ('WDC', 'WDC.US', 'USD', 'stock', 'Western Digital', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'WE', 'https://commons.wikimedia.org/wiki/Special:FilePath/WD_Logo.svg?width=160'),
  ('WY', 'WY.US', 'USD', 'stock', 'Weyerhaeuser', 'US', 'États-Unis', 'Immobilier', 'Real estate', 'realestate', 'us', 'WE', 'https://commons.wikimedia.org/wiki/Special:FilePath/Weyerhaeuser.svg?width=160'),
  ('WSM', 'WSM.US', 'USD', 'stock', 'Williams-Sonoma, Inc.', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'WI', 'https://commons.wikimedia.org/wiki/Special:FilePath/Williams-Sonoma%2C_Inc._logo.png?width=160'),
  ('WMB', 'WMB.US', 'USD', 'stock', 'Williams Companies', 'US', 'États-Unis', 'Énergie-pétrole', 'Energy and oil', 'energy', 'us', 'WI', 'https://commons.wikimedia.org/wiki/Special:FilePath/Williams_Companies_logo.svg?width=160'),
  ('WTW', 'WTW.US', 'USD', 'stock', 'Willis Towers Watson', 'US', 'États-Unis', 'Finance', 'Financials', 'finance', 'us', 'WI', null),
  ('WDAY', 'WDAY.US', 'USD', 'stock', 'Workday, Inc.', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'WO', 'https://eodhd.com/img/logos/US/wday.png'),
  ('WYNN', 'WYNN.US', 'USD', 'stock', 'Wynn Resorts', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'WY', 'https://commons.wikimedia.org/wiki/Special:FilePath/Wynn_Resorts_logo_2025.png?width=160'),
  ('XEL', 'XEL.US', 'USD', 'stock', 'Xcel Energy', 'US', 'États-Unis', 'Services aux collectivités', 'Utilities', 'energy', 'us', 'XC', 'https://eodhd.com/img/logos/US/xel.png'),
  ('XYL', 'XYL.US', 'USD', 'stock', 'Xylem Inc.', 'US', 'États-Unis', 'Industrie', 'Industrials', 'industry', 'us', 'XY', 'https://commons.wikimedia.org/wiki/Special:FilePath/Xylem_Logo.svg?width=160'),
  ('YUM', 'YUM.US', 'USD', 'stock', 'Yum! Brands', 'US', 'États-Unis', 'Consommation discrétionnaire', 'Consumer discretionary', 'consumer', 'us', 'YU', 'https://commons.wikimedia.org/wiki/Special:FilePath/Yum%21_Brands_logo.svg?width=160'),
  ('ZBRA', 'ZBRA.US', 'USD', 'stock', 'Zebra Technologies', 'US', 'États-Unis', 'Technologies de l''information', 'Information technology', 'technology', 'us', 'ZE', null),
  ('ZBH', 'ZBH.US', 'USD', 'stock', 'Zimmer Biomet', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'ZI', 'https://commons.wikimedia.org/wiki/Special:FilePath/Zimmer_Holdings_logo.svg?width=160'),
  ('ZTS', 'ZTS.US', 'USD', 'stock', 'Zoetis', 'US', 'États-Unis', 'Santé', 'Health care', 'health', 'us', 'ZO', 'https://eodhd.com/img/logos/US/zts.png')
on conflict (symbol) do update set
  logo_url = coalesce(public.securities.logo_url, excluded.logo_url);

-- Logos des titres déjà au catalogue.
update public.securities set logo_url = v.logo
from (values
  ('GOOG', 'https://eodhd.com/img/logos/US/goog.png'),
  ('AMZN', 'https://eodhd.com/img/logos/US/amzn.png'),
  ('AAPL', 'https://eodhd.com/img/logos/US/aapl.png'),
  ('BAC', 'https://eodhd.com/img/logos/US/bac.png'),
  ('BRKB', 'https://commons.wikimedia.org/wiki/Special:FilePath/Berkshire-Hathaway-Logo.svg?width=160'),
  ('JPM', 'https://commons.wikimedia.org/wiki/Special:FilePath/Logo_of_JPMorganChase_2024.svg?width=160'),
  ('MA', 'https://eodhd.com/img/logos/US/ma.png'),
  ('TSLA', 'https://commons.wikimedia.org/wiki/Special:FilePath/Tesla_Motors.svg?width=160'),
  ('V', 'https://eodhd.com/img/logos/US/v.png'),
  ('WFC', 'https://commons.wikimedia.org/wiki/Special:FilePath/Wells_Fargo_Bank.svg?width=160')
) as v(symbol, logo)
where public.securities.symbol = v.symbol
  and public.securities.logo_url is distinct from v.logo;

